// Generates lib/l10n/generated_localizations.dart from ARB files.
//
// Usage:
//   dart run tool/gen_l10n.dart
//
// Source of truth: lib/l10n/arb/app_*.arb

import 'dart:convert';
import 'dart:io';

String _dartString(String input) => jsonEncode(input).replaceAll(r'$', r'\$');

void main() {
  final arbDir = Directory('lib/l10n/arb');
  if (!arbDir.existsSync()) {
    stderr.writeln('Missing directory: ${arbDir.path}');
    exit(1);
  }

  final arbFiles = arbDir
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.arb'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  if (arbFiles.isEmpty) {
    stderr.writeln('No .arb files found in ${arbDir.path}');
    exit(1);
  }

  final Map<String, Map<String, String>> byLocale = {};

  for (final f in arbFiles) {
    final raw = f.readAsStringSync();
    final decoded = jsonDecode(raw);
    if (decoded is! Map) {
      stderr.writeln('Invalid ARB (not a JSON object): ${f.path}');
      exit(1);
    }

    final locale = decoded['@@locale']?.toString() ?? '';
    if (locale.isEmpty) {
      stderr.writeln('Missing @@locale in ${f.path}');
      exit(1);
    }

    final Map<String, String> strings = {};
    for (final entry in decoded.entries) {
      final k = entry.key.toString();
      if (k.startsWith('@')) continue; // ARB metadata.
      final v = entry.value;
      if (v is! String) {
        stderr.writeln('Non-string value for key "$k" in ${f.path}');
        exit(1);
      }
      strings[k] = v;
    }

    byLocale[locale] = strings;
  }

  // Key consistency check: all locales must match base keys.
  final baseLocale = byLocale.containsKey('en')
      ? 'en'
      : (byLocale.keys.toList()..sort()).first;
  final baseKeys = byLocale[baseLocale]!.keys.toSet();

  for (final entry in byLocale.entries) {
    final locale = entry.key;
    final keys = entry.value.keys.toSet();
    final missing = baseKeys.difference(keys).toList()..sort();
    final extra = keys.difference(baseKeys).toList()..sort();

    if (missing.isNotEmpty || extra.isNotEmpty) {
      stderr.writeln('ARB key mismatch for locale=$locale (base=$baseLocale)');
      if (missing.isNotEmpty) {
        stderr.writeln('  Missing (${missing.length}): ${missing.join(', ')}');
      }
      if (extra.isNotEmpty) {
        stderr.writeln('  Extra (${extra.length}): ${extra.join(', ')}');
      }
      exit(1);
    }
  }

  final locales = byLocale.keys.toList()..sort();

  final out = StringBuffer();
  out.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.');
  out.writeln('//');
  out.writeln('// Source: lib/l10n/arb/app_*.arb');
  out.writeln('// Generated by: tool/gen_l10n.dart');
  out.writeln();
  out.writeln('const List<String> kSupportedLocaleKeys = <String>[');
  for (final l in locales) {
    out.writeln('  ${_dartString(l)},');
  }
  out.writeln('];');
  out.writeln();
  out.writeln('const Map<String, Map<String, String>> kLocalizedValues = <String, Map<String, String>>{');

  for (final locale in locales) {
    final map = byLocale[locale]!;
    final keys = map.keys.toList()..sort();
    out.writeln('  ${_dartString(locale)}: <String, String>{');
    for (final k in keys) {
      out.writeln('    ${_dartString(k)}: ${_dartString(map[k]!)},');
    }
    out.writeln('  },');
  }

  out.writeln('};');

  final outPath = File('lib/l10n/generated_localizations.dart');
  outPath.writeAsStringSync(out.toString());

  stdout.writeln(
    'Generated ${outPath.path} (locales=${locales.length}, keys=${baseKeys.length}).',
  );
}
