import 'package:flutter/material.dart';

class CodeEditorThemePreset {
  final String id;
  final String label;
  final Map<String, TextStyle> highlightTheme;
  final bool isDark;
  final Color currentLineColor;
  final Color selectionColor;
  final Color gutterBackground;
  final Color activeLineNumberBackground;
  final Color lineNumberColor;
  final Color activeLineNumberColor;
  final Color indentGuideColor;
  final Color activeIndentGuideColor;
  final Color bracketPairColor;
  final Color rulerColor;
  final Color searchMatchBackgroundColor;
  final Color currentSearchMatchBackgroundColor;
  final Color searchMatchTextColor;

  const CodeEditorThemePreset({
    required this.id,
    required this.label,
    required this.highlightTheme,
    required this.isDark,
    required this.currentLineColor,
    required this.selectionColor,
    required this.gutterBackground,
    required this.activeLineNumberBackground,
    required this.lineNumberColor,
    required this.activeLineNumberColor,
    required this.indentGuideColor,
    required this.activeIndentGuideColor,
    required this.bracketPairColor,
    required this.rulerColor,
    required this.searchMatchBackgroundColor,
    required this.currentSearchMatchBackgroundColor,
    required this.searchMatchTextColor,
  });
}

Map<String, TextStyle> _buildTheme({
  required Color background,
  required Color foreground,
  required Color comment,
  required Color keyword,
  required Color string,
  required Color number,
  required Color variable,
  required Color type,
  required Color title,
  required Color meta,
  Color? attr,
  Color? link,
}) {
  return {
    'root': TextStyle(backgroundColor: background, color: foreground),
    'comment': TextStyle(color: comment, fontStyle: FontStyle.italic),
    'quote': TextStyle(color: comment, fontStyle: FontStyle.italic),
    'keyword': TextStyle(color: keyword),
    'selector-tag': TextStyle(color: keyword),
    'literal': TextStyle(color: number),
    'number': TextStyle(color: number),
    'string': TextStyle(color: string),
    'title': TextStyle(color: title),
    'section': TextStyle(color: title),
    'name': TextStyle(color: title),
    'function': TextStyle(color: title),
    'params': TextStyle(color: foreground),
    'type': TextStyle(color: type),
    'class': TextStyle(color: type),
    'built_in': TextStyle(color: type),
    'builtin-name': TextStyle(color: type),
    'attr': TextStyle(color: attr ?? variable),
    'attribute': TextStyle(color: attr ?? variable),
    'variable': TextStyle(color: variable),
    'template-variable': TextStyle(color: variable),
    'symbol': TextStyle(color: link ?? keyword),
    'bullet': TextStyle(color: link ?? keyword),
    'link': TextStyle(color: link ?? keyword),
    'meta': TextStyle(color: meta),
    'meta-keyword': TextStyle(color: meta),
    'subst': TextStyle(color: foreground),
    'tag': TextStyle(color: keyword),
  };
}

final List<CodeEditorThemePreset> codeEditorThemePresets = [
  CodeEditorThemePreset(
    id: 'vscode_dark',
    label: 'VS Code Dark+',
    highlightTheme: _buildTheme(
      background: const Color(0xFF1E1E1E),
      foreground: const Color(0xFFDCDCDC),
      comment: const Color(0xFF57A64A),
      keyword: const Color(0xFF569CD6),
      string: const Color(0xFFD69D85),
      number: const Color(0xFFB8D7A3),
      variable: const Color(0xFFBD63C5),
      type: const Color(0xFF4EC9B0),
      title: const Color(0xFFDCDCDC),
      meta: const Color(0xFF9B9B9B),
      attr: const Color(0xFF9CDCFE),
    ),
    isDark: true,
    currentLineColor: const Color(0xFF2A2D2E),
    selectionColor: const Color(0xFF264F78),
    gutterBackground: const Color(0xFF1E1E1E),
    activeLineNumberBackground: const Color(0xFF252526),
    lineNumberColor: const Color(0xFF858585),
    activeLineNumberColor: const Color(0xFFC6C6C6),
    indentGuideColor: const Color(0xFF404040),
    activeIndentGuideColor: const Color(0xFF707070),
    bracketPairColor: const Color(0xFF8CDCFE),
    rulerColor: const Color(0xFF333333),
    searchMatchBackgroundColor: const Color(0xFF613214),
    currentSearchMatchBackgroundColor: const Color(0xFF9E6A03),
    searchMatchTextColor: const Color(0xFFF7F7F7),
  ),
  CodeEditorThemePreset(
    id: 'vscode_light',
    label: 'VS Code Light+',
    highlightTheme: _buildTheme(
      background: const Color(0xFFFFFFFF),
      foreground: const Color(0xFF000000),
      comment: const Color(0xFF008000),
      keyword: const Color(0xFF0000FF),
      string: const Color(0xFFA31515),
      number: const Color(0xFF098658),
      variable: const Color(0xFF001080),
      type: const Color(0xFF267F99),
      title: const Color(0xFF795E26),
      meta: const Color(0xFF2B91AF),
      attr: const Color(0xFFE50000),
    ),
    isDark: false,
    currentLineColor: const Color(0xFFEFF3F8),
    selectionColor: const Color(0xFFBBD8FB),
    gutterBackground: const Color(0xFFF7F9FC),
    activeLineNumberBackground: const Color(0xFFE8EEF6),
    lineNumberColor: const Color(0xFF616161),
    activeLineNumberColor: const Color(0xFF1F2328),
    indentGuideColor: const Color(0xFFD6DCE5),
    activeIndentGuideColor: const Color(0xFF9AA4B2),
    bracketPairColor: const Color(0xFF0F6CBD),
    rulerColor: const Color(0xFFE0E6EE),
    searchMatchBackgroundColor: const Color(0xFFFFE59A),
    currentSearchMatchBackgroundColor: const Color(0xFFF8C555),
    searchMatchTextColor: const Color(0xFF1F2328),
  ),
  CodeEditorThemePreset(
    id: 'one_dark',
    label: 'One Dark Pro',
    highlightTheme: _buildTheme(
      background: const Color(0xFF282C34),
      foreground: const Color(0xFFABB2BF),
      comment: const Color(0xFF5C6370),
      keyword: const Color(0xFFC678DD),
      string: const Color(0xFF98C379),
      number: const Color(0xFFD19A66),
      variable: const Color(0xFFD19A66),
      type: const Color(0xFFE5C07B),
      title: const Color(0xFF61AFEF),
      meta: const Color(0xFF61AFEF),
      attr: const Color(0xFF98C379),
    ),
    isDark: true,
    currentLineColor: const Color(0xFF2C313C),
    selectionColor: const Color(0xFF3E4451),
    gutterBackground: const Color(0xFF21252B),
    activeLineNumberBackground: const Color(0xFF2A2F37),
    lineNumberColor: const Color(0xFF636D83),
    activeLineNumberColor: const Color(0xFFABB2BF),
    indentGuideColor: const Color(0xFF3A404B),
    activeIndentGuideColor: const Color(0xFF59606D),
    bracketPairColor: const Color(0xFF61AFEF),
    rulerColor: const Color(0xFF353B45),
    searchMatchBackgroundColor: const Color(0xFF6B5330),
    currentSearchMatchBackgroundColor: const Color(0xFFC18F2B),
    searchMatchTextColor: const Color(0xFFF3F4F6),
  ),
  CodeEditorThemePreset(
    id: 'one_light',
    label: 'One Light',
    highlightTheme: _buildTheme(
      background: const Color(0xFFFAFBFC),
      foreground: const Color(0xFF383A42),
      comment: const Color(0xFFA0A1A7),
      keyword: const Color(0xFFA626A4),
      string: const Color(0xFF50A14F),
      number: const Color(0xFF986801),
      variable: const Color(0xFFE45649),
      type: const Color(0xFFC18401),
      title: const Color(0xFF4078F2),
      meta: const Color(0xFF4078F2),
      attr: const Color(0xFF50A14F),
    ),
    isDark: false,
    currentLineColor: const Color(0xFFF0F4F8),
    selectionColor: const Color(0xFFD9E9FF),
    gutterBackground: const Color(0xFFFAFBFC),
    activeLineNumberBackground: const Color(0xFFECEFF4),
    lineNumberColor: const Color(0xFF6A737D),
    activeLineNumberColor: const Color(0xFF24292E),
    indentGuideColor: const Color(0xFFD4DAE3),
    activeIndentGuideColor: const Color(0xFF97A1AF),
    bracketPairColor: const Color(0xFF4078F2),
    rulerColor: const Color(0xFFE2E7EE),
    searchMatchBackgroundColor: const Color(0xFFFFE8A3),
    currentSearchMatchBackgroundColor: const Color(0xFFF4C95D),
    searchMatchTextColor: const Color(0xFF1B1F24),
  ),
  CodeEditorThemePreset(
    id: 'github_light',
    label: 'GitHub Light',
    highlightTheme: _buildTheme(
      background: const Color(0xFFF8F8F8),
      foreground: const Color(0xFF333333),
      comment: const Color(0xFF999988),
      keyword: const Color(0xFF333333),
      string: const Color(0xFFDD1144),
      number: const Color(0xFF008080),
      variable: const Color(0xFF008080),
      type: const Color(0xFF445588),
      title: const Color(0xFF990000),
      meta: const Color(0xFF999999),
      attr: const Color(0xFF000080),
    ),
    isDark: false,
    currentLineColor: const Color(0xFFF6F8FA),
    selectionColor: const Color(0xFFDDEBFF),
    gutterBackground: const Color(0xFFF6F8FA),
    activeLineNumberBackground: const Color(0xFFEAEEF2),
    lineNumberColor: const Color(0xFF6E7781),
    activeLineNumberColor: const Color(0xFF24292F),
    indentGuideColor: const Color(0xFFD0D7DE),
    activeIndentGuideColor: const Color(0xFF8C959F),
    bracketPairColor: const Color(0xFF0969DA),
    rulerColor: const Color(0xFFE1E4E8),
    searchMatchBackgroundColor: const Color(0xFFFFE58F),
    currentSearchMatchBackgroundColor: const Color(0xFFF2C94C),
    searchMatchTextColor: const Color(0xFF24292F),
  ),
  CodeEditorThemePreset(
    id: 'a11y_light',
    label: 'A11y Light',
    highlightTheme: _buildTheme(
      background: const Color(0xFFFFFFFF),
      foreground: const Color(0xFF1B1B1B),
      comment: const Color(0xFF696969),
      keyword: const Color(0xFF7928A1),
      string: const Color(0xFF008000),
      number: const Color(0xFFAA5D00),
      variable: const Color(0xFFD91E18),
      type: const Color(0xFF005A9C),
      title: const Color(0xFF005A9C),
      meta: const Color(0xFFAA5D00),
      attr: const Color(0xFFAA5D00),
    ),
    isDark: false,
    currentLineColor: const Color(0xFFF4F6F8),
    selectionColor: const Color(0xFFD6E6FF),
    gutterBackground: const Color(0xFFFCFCFC),
    activeLineNumberBackground: const Color(0xFFF0F3F6),
    lineNumberColor: const Color(0xFF575757),
    activeLineNumberColor: const Color(0xFF111111),
    indentGuideColor: const Color(0xFFD0D7DE),
    activeIndentGuideColor: const Color(0xFF8C959F),
    bracketPairColor: const Color(0xFF0550AE),
    rulerColor: const Color(0xFFE5EAF0),
    searchMatchBackgroundColor: const Color(0xFFFFE8A3),
    currentSearchMatchBackgroundColor: const Color(0xFFF2C94C),
    searchMatchTextColor: const Color(0xFF111827),
  ),
  CodeEditorThemePreset(
    id: 'gruvbox_dark',
    label: 'Gruvbox Dark',
    highlightTheme: _buildTheme(
      background: const Color(0xFF282828),
      foreground: const Color(0xFFEBDBB2),
      comment: const Color(0xFF928374),
      keyword: const Color(0xFFFB4934),
      string: const Color(0xFFB8BB26),
      number: const Color(0xFFD3869B),
      variable: const Color(0xFFFABD2F),
      type: const Color(0xFF8EC07C),
      title: const Color(0xFF83A598),
      meta: const Color(0xFFFE8019),
      attr: const Color(0xFF8EC07C),
    ),
    isDark: true,
    currentLineColor: const Color(0xFF3C3836),
    selectionColor: const Color(0xFF504945),
    gutterBackground: const Color(0xFF282828),
    activeLineNumberBackground: const Color(0xFF32302F),
    lineNumberColor: const Color(0xFF928374),
    activeLineNumberColor: const Color(0xFFEBDBB2),
    indentGuideColor: const Color(0xFF504945),
    activeIndentGuideColor: const Color(0xFF7C6F64),
    bracketPairColor: const Color(0xFF83A598),
    rulerColor: const Color(0xFF3A3634),
    searchMatchBackgroundColor: const Color(0xFF665C2D),
    currentSearchMatchBackgroundColor: const Color(0xFFD79921),
    searchMatchTextColor: const Color(0xFF1D2021),
  ),
  CodeEditorThemePreset(
    id: 'gruvbox_light',
    label: 'Gruvbox Light',
    highlightTheme: _buildTheme(
      background: const Color(0xFFF9F5D7),
      foreground: const Color(0xFF3C3836),
      comment: const Color(0xFF928374),
      keyword: const Color(0xFF9D0006),
      string: const Color(0xFF79740E),
      number: const Color(0xFF8F3F71),
      variable: const Color(0xFFB57614),
      type: const Color(0xFF427B58),
      title: const Color(0xFF076678),
      meta: const Color(0xFFAF3A03),
      attr: const Color(0xFF427B58),
    ),
    isDark: false,
    currentLineColor: const Color(0xFFF2E5BC),
    selectionColor: const Color(0xFFE5D5A4),
    gutterBackground: const Color(0xFFF9F5D7),
    activeLineNumberBackground: const Color(0xFFF0E0B4),
    lineNumberColor: const Color(0xFF7C6F64),
    activeLineNumberColor: const Color(0xFF3C3836),
    indentGuideColor: const Color(0xFFD5C4A1),
    activeIndentGuideColor: const Color(0xFFBDAE93),
    bracketPairColor: const Color(0xFF076678),
    rulerColor: const Color(0xFFE8DFC4),
    searchMatchBackgroundColor: const Color(0xFFF1D88A),
    currentSearchMatchBackgroundColor: const Color(0xFFD79921),
    searchMatchTextColor: const Color(0xFF3C3836),
  ),
  CodeEditorThemePreset(
    id: 'monokai',
    label: 'Monokai',
    highlightTheme: _buildTheme(
      background: const Color(0xFF23241F),
      foreground: const Color(0xFFF8F8F2),
      comment: const Color(0xFF75715E),
      keyword: const Color(0xFFF92672),
      string: const Color(0xFFE6DB74),
      number: const Color(0xFFAE81FF),
      variable: const Color(0xFFE6DB74),
      type: const Color(0xFFE6DB74),
      title: const Color(0xFFA6E22E),
      meta: const Color(0xFF75715E),
      attr: const Color(0xFF66D9EF),
    ),
    isDark: true,
    currentLineColor: const Color(0xFF2B2C27),
    selectionColor: const Color(0xFF49483E),
    gutterBackground: const Color(0xFF23241F),
    activeLineNumberBackground: const Color(0xFF2F3129),
    lineNumberColor: const Color(0xFF75715E),
    activeLineNumberColor: const Color(0xFFF8F8F2),
    indentGuideColor: const Color(0xFF414339),
    activeIndentGuideColor: const Color(0xFF6B705B),
    bracketPairColor: const Color(0xFF66D9EF),
    rulerColor: const Color(0xFF3A3C34),
    searchMatchBackgroundColor: const Color(0xFF665B2C),
    currentSearchMatchBackgroundColor: const Color(0xFFE6DB74),
    searchMatchTextColor: const Color(0xFF1E1F1C),
  ),
  CodeEditorThemePreset(
    id: 'dracula',
    label: 'Dracula',
    highlightTheme: _buildTheme(
      background: const Color(0xFF282A36),
      foreground: const Color(0xFFF8F8F2),
      comment: const Color(0xFF6272A4),
      keyword: const Color(0xFF8BE9FD),
      string: const Color(0xFFF1FA8C),
      number: const Color(0xFFBD93F9),
      variable: const Color(0xFFF1FA8C),
      type: const Color(0xFFF1FA8C),
      title: const Color(0xFFF1FA8C),
      meta: const Color(0xFF6272A4),
      attr: const Color(0xFFF1FA8C),
    ),
    isDark: true,
    currentLineColor: const Color(0xFF343746),
    selectionColor: const Color(0xFF44475A),
    gutterBackground: const Color(0xFF282A36),
    activeLineNumberBackground: const Color(0xFF303341),
    lineNumberColor: const Color(0xFF6272A4),
    activeLineNumberColor: const Color(0xFFF8F8F2),
    indentGuideColor: const Color(0xFF44475A),
    activeIndentGuideColor: const Color(0xFF6272A4),
    bracketPairColor: const Color(0xFFBD93F9),
    rulerColor: const Color(0xFF3A3D4D),
    searchMatchBackgroundColor: const Color(0xFF5C4B1B),
    currentSearchMatchBackgroundColor: const Color(0xFFF1FA8C),
    searchMatchTextColor: const Color(0xFF1E1F29),
  ),
  CodeEditorThemePreset(
    id: 'nord',
    label: 'Nord',
    highlightTheme: _buildTheme(
      background: const Color(0xFF2E3440),
      foreground: const Color(0xFFD8DEE9),
      comment: const Color(0xFF4C566A),
      keyword: const Color(0xFF81A1C1),
      string: const Color(0xFFA3BE8C),
      number: const Color(0xFFB48EAD),
      variable: const Color(0xFFD8DEE9),
      type: const Color(0xFF8FBCBB),
      title: const Color(0xFF88C0D0),
      meta: const Color(0xFF5E81AC),
      attr: const Color(0xFF8FBCBB),
    ),
    isDark: true,
    currentLineColor: const Color(0xFF3B4252),
    selectionColor: const Color(0xFF434C5E),
    gutterBackground: const Color(0xFF2E3440),
    activeLineNumberBackground: const Color(0xFF3A4150),
    lineNumberColor: const Color(0xFF7D8796),
    activeLineNumberColor: const Color(0xFFE5E9F0),
    indentGuideColor: const Color(0xFF4C566A),
    activeIndentGuideColor: const Color(0xFF81A1C1),
    bracketPairColor: const Color(0xFF88C0D0),
    rulerColor: const Color(0xFF434C5E),
    searchMatchBackgroundColor: const Color(0xFF5E5A2F),
    currentSearchMatchBackgroundColor: const Color(0xFFEBCB8B),
    searchMatchTextColor: const Color(0xFF1F2937),
  ),
  CodeEditorThemePreset(
    id: 'night_owl',
    label: 'Night Owl',
    highlightTheme: _buildTheme(
      background: const Color(0xFF011627),
      foreground: const Color(0xFFD6DEEB),
      comment: const Color(0xFF637777),
      keyword: const Color(0xFFC792EA),
      string: const Color(0xFFECC48D),
      number: const Color(0xFFF78C6C),
      variable: const Color(0xFFD6DEEB),
      type: const Color(0xFF82AAFF),
      title: const Color(0xFFDCDCAA),
      meta: const Color(0xFF82AAFF),
      attr: const Color(0xFFADDB67),
    ),
    isDark: true,
    currentLineColor: const Color(0xFF102338),
    selectionColor: const Color(0xFF1D3B53),
    gutterBackground: const Color(0xFF011627),
    activeLineNumberBackground: const Color(0xFF0B2137),
    lineNumberColor: const Color(0xFF5F7E97),
    activeLineNumberColor: const Color(0xFFD6DEEB),
    indentGuideColor: const Color(0xFF1D3B53),
    activeIndentGuideColor: const Color(0xFF82AAFF),
    bracketPairColor: const Color(0xFF7FDBCA),
    rulerColor: const Color(0xFF16314B),
    searchMatchBackgroundColor: const Color(0xFF5E5324),
    currentSearchMatchBackgroundColor: const Color(0xFFECC48D),
    searchMatchTextColor: const Color(0xFF0B1320),
  ),
  CodeEditorThemePreset(
    id: 'a11y_dark',
    label: 'A11y Dark',
    highlightTheme: _buildTheme(
      background: const Color(0xFF1B1B1B),
      foreground: const Color(0xFFF8F8F2),
      comment: const Color(0xFFD4D0AB),
      keyword: const Color(0xFFFFFFA0),
      string: const Color(0xFFABE338),
      number: const Color(0xFFF5AB35),
      variable: const Color(0xFFFFA07A),
      type: const Color(0xFFFFD700),
      title: const Color(0xFFFFD700),
      meta: const Color(0xFFF5AB35),
      attr: const Color(0xFFFFD700),
    ),
    isDark: true,
    currentLineColor: const Color(0xFF1F1F24),
    selectionColor: const Color(0xFF2F333A),
    gutterBackground: const Color(0xFF1B1B1B),
    activeLineNumberBackground: const Color(0xFF252525),
    lineNumberColor: const Color(0xFFCAC59D),
    activeLineNumberColor: const Color(0xFFFFF4BF),
    indentGuideColor: const Color(0xFF4C4C4C),
    activeIndentGuideColor: const Color(0xFFFFD700),
    bracketPairColor: const Color(0xFFFFA07A),
    rulerColor: const Color(0xFF343434),
    searchMatchBackgroundColor: const Color(0xFF6C5A21),
    currentSearchMatchBackgroundColor: const Color(0xFFF5AB35),
    searchMatchTextColor: const Color(0xFF111111),
  ),
];

CodeEditorThemePreset codeEditorThemePresetById(String id) {
  return codeEditorThemePresets.firstWhere(
    (preset) => preset.id == id,
    orElse: () => codeEditorThemePresets.first,
  );
}

List<CodeEditorThemePreset> get lightCodeEditorThemePresets =>
    codeEditorThemePresets
        .where((preset) => !preset.isDark)
        .toList(growable: false);

List<CodeEditorThemePreset> get darkCodeEditorThemePresets =>
    codeEditorThemePresets
        .where((preset) => preset.isDark)
        .toList(growable: false);
