const List<Map<String, Object>> kCodeEditorThemeSpecs = [
  {
    'id': 'vscode_dark',
    'label': 'VS Code Dark+',
    'isDark': true,
    'tokens': {
      'background': '#1E1E1E',
      'foreground': '#DCDCDC',
      'comment': '#57A64A',
      'keyword': '#569CD6',
      'string': '#D69D85',
      'number': '#B8D7A3',
      'variable': '#BD63C5',
      'type': '#4EC9B0',
      'title': '#DCDCDC',
      'meta': '#9B9B9B',
      'attr': '#9CDCFE',
    },
    'ui': {
      'currentLineColor': '#2A2D2E',
      'selectionColor': '#264F78',
      'gutterBackground': '#1E1E1E',
      'activeLineNumberBackground': '#252526',
      'lineNumberColor': '#858585',
      'activeLineNumberColor': '#C6C6C6',
      'indentGuideColor': '#404040',
      'activeIndentGuideColor': '#707070',
      'bracketPairColor': '#8CDCFE',
      'rulerColor': '#333333',
      'searchMatchBackgroundColor': '#613214',
      'currentSearchMatchBackgroundColor': '#9E6A03',
      'searchMatchTextColor': '#F7F7F7',
    },
  },
  {
    'id': 'vscode_light',
    'label': 'VS Code Light+',
    'isDark': false,
    'tokens': {
      'background': '#FFFFFF',
      'foreground': '#000000',
      'comment': '#008000',
      'keyword': '#0000FF',
      'string': '#A31515',
      'number': '#098658',
      'variable': '#001080',
      'type': '#267F99',
      'title': '#795E26',
      'meta': '#2B91AF',
      'attr': '#E50000',
    },
    'ui': {
      'currentLineColor': '#EFF3F8',
      'selectionColor': '#BBD8FB',
      'gutterBackground': '#F7F9FC',
      'activeLineNumberBackground': '#E8EEF6',
      'lineNumberColor': '#616161',
      'activeLineNumberColor': '#1F2328',
      'indentGuideColor': '#D6DCE5',
      'activeIndentGuideColor': '#9AA4B2',
      'bracketPairColor': '#0F6CBD',
      'rulerColor': '#E0E6EE',
      'searchMatchBackgroundColor': '#FFE59A',
      'currentSearchMatchBackgroundColor': '#F8C555',
      'searchMatchTextColor': '#1F2328',
    },
  },
  {
    'id': 'one_dark',
    'label': 'One Dark Pro',
    'isDark': true,
    'tokens': {
      'background': '#282C34',
      'foreground': '#ABB2BF',
      'comment': '#5C6370',
      'keyword': '#C678DD',
      'string': '#98C379',
      'number': '#D19A66',
      'variable': '#D19A66',
      'type': '#E5C07B',
      'title': '#61AFEF',
      'meta': '#61AFEF',
      'attr': '#98C379',
    },
    'ui': {
      'currentLineColor': '#2C313C',
      'selectionColor': '#3E4451',
      'gutterBackground': '#21252B',
      'activeLineNumberBackground': '#2A2F37',
      'lineNumberColor': '#636D83',
      'activeLineNumberColor': '#ABB2BF',
      'indentGuideColor': '#3A404B',
      'activeIndentGuideColor': '#59606D',
      'bracketPairColor': '#61AFEF',
      'rulerColor': '#353B45',
      'searchMatchBackgroundColor': '#6B5330',
      'currentSearchMatchBackgroundColor': '#C18F2B',
      'searchMatchTextColor': '#F3F4F6',
    },
  },
  {
    'id': 'one_light',
    'label': 'One Light',
    'isDark': false,
    'tokens': {
      'background': '#FAFBFC',
      'foreground': '#383A42',
      'comment': '#A0A1A7',
      'keyword': '#A626A4',
      'string': '#50A14F',
      'number': '#986801',
      'variable': '#E45649',
      'type': '#C18401',
      'title': '#4078F2',
      'meta': '#4078F2',
      'attr': '#50A14F',
    },
    'ui': {
      'currentLineColor': '#F0F4F8',
      'selectionColor': '#D9E9FF',
      'gutterBackground': '#FAFBFC',
      'activeLineNumberBackground': '#ECEFF4',
      'lineNumberColor': '#6A737D',
      'activeLineNumberColor': '#24292E',
      'indentGuideColor': '#D4DAE3',
      'activeIndentGuideColor': '#97A1AF',
      'bracketPairColor': '#4078F2',
      'rulerColor': '#E2E7EE',
      'searchMatchBackgroundColor': '#FFE8A3',
      'currentSearchMatchBackgroundColor': '#F4C95D',
      'searchMatchTextColor': '#1B1F24',
    },
  },
  {
    'id': 'github_light',
    'label': 'GitHub Light',
    'isDark': false,
    'tokens': {
      'background': '#F8F8F8',
      'foreground': '#333333',
      'comment': '#999988',
      'keyword': '#333333',
      'string': '#DD1144',
      'number': '#008080',
      'variable': '#008080',
      'type': '#445588',
      'title': '#990000',
      'meta': '#999999',
      'attr': '#000080',
    },
    'ui': {
      'currentLineColor': '#F6F8FA',
      'selectionColor': '#DDEBFF',
      'gutterBackground': '#F6F8FA',
      'activeLineNumberBackground': '#EAEEF2',
      'lineNumberColor': '#6E7781',
      'activeLineNumberColor': '#24292F',
      'indentGuideColor': '#D0D7DE',
      'activeIndentGuideColor': '#8C959F',
      'bracketPairColor': '#0969DA',
      'rulerColor': '#E1E4E8',
      'searchMatchBackgroundColor': '#FFE58F',
      'currentSearchMatchBackgroundColor': '#F2C94C',
      'searchMatchTextColor': '#24292F',
    },
  },
  {
    'id': 'a11y_light',
    'label': 'A11y Light',
    'isDark': false,
    'tokens': {
      'background': '#FFFFFF',
      'foreground': '#1B1B1B',
      'comment': '#696969',
      'keyword': '#7928A1',
      'string': '#008000',
      'number': '#AA5D00',
      'variable': '#D91E18',
      'type': '#005A9C',
      'title': '#005A9C',
      'meta': '#AA5D00',
      'attr': '#AA5D00',
    },
    'ui': {
      'currentLineColor': '#F4F6F8',
      'selectionColor': '#D6E6FF',
      'gutterBackground': '#FCFCFC',
      'activeLineNumberBackground': '#F0F3F6',
      'lineNumberColor': '#575757',
      'activeLineNumberColor': '#111111',
      'indentGuideColor': '#D0D7DE',
      'activeIndentGuideColor': '#8C959F',
      'bracketPairColor': '#0550AE',
      'rulerColor': '#E5EAF0',
      'searchMatchBackgroundColor': '#FFE8A3',
      'currentSearchMatchBackgroundColor': '#F2C94C',
      'searchMatchTextColor': '#111827',
    },
  },
  {
    'id': 'gruvbox_dark',
    'label': 'Gruvbox Dark',
    'isDark': true,
    'tokens': {
      'background': '#282828',
      'foreground': '#EBDBB2',
      'comment': '#928374',
      'keyword': '#FB4934',
      'string': '#B8BB26',
      'number': '#D3869B',
      'variable': '#FABD2F',
      'type': '#8EC07C',
      'title': '#83A598',
      'meta': '#FE8019',
      'attr': '#8EC07C',
    },
    'ui': {
      'currentLineColor': '#3C3836',
      'selectionColor': '#504945',
      'gutterBackground': '#282828',
      'activeLineNumberBackground': '#32302F',
      'lineNumberColor': '#928374',
      'activeLineNumberColor': '#EBDBB2',
      'indentGuideColor': '#504945',
      'activeIndentGuideColor': '#7C6F64',
      'bracketPairColor': '#83A598',
      'rulerColor': '#3A3634',
      'searchMatchBackgroundColor': '#665C2D',
      'currentSearchMatchBackgroundColor': '#D79921',
      'searchMatchTextColor': '#1D2021',
    },
  },
  {
    'id': 'gruvbox_light',
    'label': 'Gruvbox Light',
    'isDark': false,
    'tokens': {
      'background': '#F9F5D7',
      'foreground': '#3C3836',
      'comment': '#928374',
      'keyword': '#9D0006',
      'string': '#79740E',
      'number': '#8F3F71',
      'variable': '#B57614',
      'type': '#427B58',
      'title': '#076678',
      'meta': '#AF3A03',
      'attr': '#427B58',
    },
    'ui': {
      'currentLineColor': '#F2E5BC',
      'selectionColor': '#E5D5A4',
      'gutterBackground': '#F9F5D7',
      'activeLineNumberBackground': '#F0E0B4',
      'lineNumberColor': '#7C6F64',
      'activeLineNumberColor': '#3C3836',
      'indentGuideColor': '#D5C4A1',
      'activeIndentGuideColor': '#BDAE93',
      'bracketPairColor': '#076678',
      'rulerColor': '#E8DFC4',
      'searchMatchBackgroundColor': '#F1D88A',
      'currentSearchMatchBackgroundColor': '#D79921',
      'searchMatchTextColor': '#3C3836',
    },
  },
  {
    'id': 'monokai',
    'label': 'Monokai',
    'isDark': true,
    'tokens': {
      'background': '#23241F',
      'foreground': '#F8F8F2',
      'comment': '#75715E',
      'keyword': '#F92672',
      'string': '#E6DB74',
      'number': '#AE81FF',
      'variable': '#E6DB74',
      'type': '#E6DB74',
      'title': '#A6E22E',
      'meta': '#75715E',
      'attr': '#66D9EF',
    },
    'ui': {
      'currentLineColor': '#2B2C27',
      'selectionColor': '#49483E',
      'gutterBackground': '#23241F',
      'activeLineNumberBackground': '#2F3129',
      'lineNumberColor': '#75715E',
      'activeLineNumberColor': '#F8F8F2',
      'indentGuideColor': '#414339',
      'activeIndentGuideColor': '#6B705B',
      'bracketPairColor': '#66D9EF',
      'rulerColor': '#3A3C34',
      'searchMatchBackgroundColor': '#665B2C',
      'currentSearchMatchBackgroundColor': '#E6DB74',
      'searchMatchTextColor': '#1E1F1C',
    },
  },
  {
    'id': 'dracula',
    'label': 'Dracula',
    'isDark': true,
    'tokens': {
      'background': '#282A36',
      'foreground': '#F8F8F2',
      'comment': '#6272A4',
      'keyword': '#8BE9FD',
      'string': '#F1FA8C',
      'number': '#BD93F9',
      'variable': '#F1FA8C',
      'type': '#F1FA8C',
      'title': '#F1FA8C',
      'meta': '#6272A4',
      'attr': '#F1FA8C',
    },
    'ui': {
      'currentLineColor': '#343746',
      'selectionColor': '#44475A',
      'gutterBackground': '#282A36',
      'activeLineNumberBackground': '#303341',
      'lineNumberColor': '#6272A4',
      'activeLineNumberColor': '#F8F8F2',
      'indentGuideColor': '#44475A',
      'activeIndentGuideColor': '#6272A4',
      'bracketPairColor': '#BD93F9',
      'rulerColor': '#3A3D4D',
      'searchMatchBackgroundColor': '#5C4B1B',
      'currentSearchMatchBackgroundColor': '#F1FA8C',
      'searchMatchTextColor': '#1E1F29',
    },
  },
  {
    'id': 'nord',
    'label': 'Nord',
    'isDark': true,
    'tokens': {
      'background': '#2E3440',
      'foreground': '#D8DEE9',
      'comment': '#4C566A',
      'keyword': '#81A1C1',
      'string': '#A3BE8C',
      'number': '#B48EAD',
      'variable': '#D8DEE9',
      'type': '#8FBCBB',
      'title': '#88C0D0',
      'meta': '#5E81AC',
      'attr': '#8FBCBB',
    },
    'ui': {
      'currentLineColor': '#3B4252',
      'selectionColor': '#434C5E',
      'gutterBackground': '#2E3440',
      'activeLineNumberBackground': '#3A4150',
      'lineNumberColor': '#7D8796',
      'activeLineNumberColor': '#E5E9F0',
      'indentGuideColor': '#4C566A',
      'activeIndentGuideColor': '#81A1C1',
      'bracketPairColor': '#88C0D0',
      'rulerColor': '#434C5E',
      'searchMatchBackgroundColor': '#5E5A2F',
      'currentSearchMatchBackgroundColor': '#EBCB8B',
      'searchMatchTextColor': '#1F2937',
    },
  },
  {
    'id': 'night_owl',
    'label': 'Night Owl',
    'isDark': true,
    'tokens': {
      'background': '#011627',
      'foreground': '#D6DEEB',
      'comment': '#637777',
      'keyword': '#C792EA',
      'string': '#ECC48D',
      'number': '#F78C6C',
      'variable': '#D6DEEB',
      'type': '#82AAFF',
      'title': '#DCDCAA',
      'meta': '#82AAFF',
      'attr': '#ADDB67',
    },
    'ui': {
      'currentLineColor': '#102338',
      'selectionColor': '#1D3B53',
      'gutterBackground': '#011627',
      'activeLineNumberBackground': '#0B2137',
      'lineNumberColor': '#5F7E97',
      'activeLineNumberColor': '#D6DEEB',
      'indentGuideColor': '#1D3B53',
      'activeIndentGuideColor': '#82AAFF',
      'bracketPairColor': '#7FDBCA',
      'rulerColor': '#16314B',
      'searchMatchBackgroundColor': '#5E5324',
      'currentSearchMatchBackgroundColor': '#ECC48D',
      'searchMatchTextColor': '#0B1320',
    },
  },
  {
    'id': 'a11y_dark',
    'label': 'A11y Dark',
    'isDark': true,
    'tokens': {
      'background': '#1B1B1B',
      'foreground': '#F8F8F2',
      'comment': '#D4D0AB',
      'keyword': '#FFFFA0',
      'string': '#ABE338',
      'number': '#F5AB35',
      'variable': '#FFA07A',
      'type': '#FFD700',
      'title': '#FFD700',
      'meta': '#F5AB35',
      'attr': '#FFD700',
    },
    'ui': {
      'currentLineColor': '#1F1F24',
      'selectionColor': '#2F333A',
      'gutterBackground': '#1B1B1B',
      'activeLineNumberBackground': '#252525',
      'lineNumberColor': '#CAC59D',
      'activeLineNumberColor': '#FFF4BF',
      'indentGuideColor': '#4C4C4C',
      'activeIndentGuideColor': '#FFD700',
      'bracketPairColor': '#FFA07A',
      'rulerColor': '#343434',
      'searchMatchBackgroundColor': '#6C5A21',
      'currentSearchMatchBackgroundColor': '#F5AB35',
      'searchMatchTextColor': '#111111',
    },
  },
];
