// GENERATED CODE - DO NOT MODIFY BY HAND.
//
// Source: lib/l10n/arb/app_*.arb
// Generated by: tool/gen_l10n.dart

const List<String> kSupportedLocaleKeys = <String>[
  "ar",
  "en",
  "es",
  "fr",
  "ja",
  "ru",
  "zh",
  "zh_Hant",
];

const Map<String, Map<String, String>> kLocalizedValues = <String, Map<String, String>>{
  "ar": <String, String>{
    "about": "Ø­ÙÙ",
    "about_description": "ÙÙØµØ© ØªØ·ÙÙØ± ØªØ·Ø¨ÙÙØ§Øª ØªØ¹ÙÙ Ø¨Ø§ÙØ°ÙØ§Ø¡ Ø§ÙØ§ØµØ·ÙØ§Ø¹Ù.",
    "about_subtitle": "Ø¥ØµØ¯Ø§Ø± Ø§ÙØªØ·Ø¨ÙÙ ÙØ§ÙÙØ¹ÙÙÙØ§Øª",
    "about_title": "Ø­ÙÙ",
    "activity": "Ø§ÙÙØ´Ø§Ø·",
    "agree_terms": "Ø¨ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙØ ÙØ¥ÙÙ ØªÙØ§ÙÙ Ø¹ÙÙ Ø´Ø±ÙØ· Ø§ÙØ®Ø¯ÙØ© ÙØ³ÙØ§Ø³Ø© Ø§ÙØ®ØµÙØµÙØ©",
    "api_settings": "ÙØ§Ø¬ÙØ© Ø¨Ø±ÙØ¬Ø© Ø§ÙØªØ·Ø¨ÙÙØ§Øª (API)",
    "appearance": "Ø§ÙÙØ¸ÙØ±",
    "basic_information": "Ø§ÙÙØ¹ÙÙÙØ§Øª Ø§ÙØ£Ø³Ø§Ø³ÙØ©",
    "be_first_to_share": "ÙÙ Ø£ÙÙ ÙÙ ÙØ´Ø§Ø±Ù Ø´ÙØ¦Ø§Ù!",
    "bind_email": "Ø±Ø¨Ø· Ø§ÙØ¨Ø±ÙØ¯ Ø§ÙØ¥ÙÙØªØ±ÙÙÙ",
    "bind_email_subtitle": "Ø±Ø¨Ø· Ø§ÙØ¨Ø±ÙØ¯ Ø§ÙØ¥ÙÙØªØ±ÙÙÙ Ø¨Ø­Ø³Ø§Ø¨Ù",
    "cancel": "Ø¥ÙØºØ§Ø¡",
    "choose_theme": "Ø§Ø®ØªØ± Ø§ÙÙØ¸ÙØ±",
    "code_sent_success": "ØªÙ Ø¥Ø±Ø³Ø§Ù Ø§ÙØ±ÙØ² Ø¨ÙØ¬Ø§Ø­",
    "code_sent_to": "ØªÙ Ø§ÙØ¥Ø±Ø³Ø§Ù Ø¥ÙÙ",
    "community": "Ø§ÙÙØ¬ØªÙØ¹",
    "company_name": "Ø§Ø³Ù Ø§ÙØ´Ø±ÙØ©",
    "company_website": "ÙÙÙØ¹ Ø§ÙØ´Ø±ÙØ©",
    "confirm": "ØªØ£ÙÙØ¯",
    "confirm_password": "ØªØ£ÙÙØ¯ ÙÙÙØ© Ø§ÙÙØ±ÙØ±",
    "connect_github": "Ø§ØªØµØ§Ù GitHub",
    "contact_support": "Ø§ØªØµÙ Ø¨Ø§ÙØ¯Ø¹Ù",
    "copied": "ØªÙ Ø§ÙÙØ³Ø®",
    "create_project": "Ø¥ÙØ´Ø§Ø¡ ÙØ´Ø±ÙØ¹",
    "dark_mode": "Ø§ÙÙØ¶Ø¹ Ø§ÙØ¯Ø§ÙÙ",
    "dashboard": "ÙÙØ­Ø© Ø§ÙØªØ­ÙÙ",
    "delete": "Ø­Ø°Ù",
    "docs": "Ø§ÙÙØ³ØªÙØ¯Ø§Øª",
    "edit": "ØªØ¹Ø¯ÙÙ",
    "edit_profile": "ØªØ¹Ø¯ÙÙ Ø§ÙÙÙÙ Ø§ÙØ´Ø®ØµÙ",
    "email": "Ø§ÙØ¨Ø±ÙØ¯ Ø§ÙØ¥ÙÙØªØ±ÙÙÙ",
    "email_address": "Ø¹ÙÙØ§Ù Ø§ÙØ¨Ø±ÙØ¯ Ø§ÙØ¥ÙÙØªØ±ÙÙÙ",
    "email_bound_success": "ØªÙ Ø±Ø¨Ø· Ø§ÙØ¨Ø±ÙØ¯ Ø§ÙØ¥ÙÙØªØ±ÙÙÙ Ø¨ÙØ¬Ø§Ø­",
    "email_invalid": "ÙØ±Ø¬Ù Ø¥Ø¯Ø®Ø§Ù Ø¹ÙÙØ§Ù Ø¨Ø±ÙØ¯ Ø¥ÙÙØªØ±ÙÙÙ ØµØ§ÙØ­",
    "email_required": "ÙØ±Ø¬Ù Ø¥Ø¯Ø®Ø§Ù Ø¹ÙÙØ§Ù Ø§ÙØ¨Ø±ÙØ¯ Ø§ÙØ¥ÙÙØªØ±ÙÙÙ",
    "enter_code_and_new_password": "Ø£Ø¯Ø®Ù Ø§ÙØ±ÙØ² ÙÙÙÙØ© Ø§ÙÙØ±ÙØ± Ø§ÙØ¬Ø¯ÙØ¯Ø©",
    "enter_code_sent": "Ø£Ø¯Ø®Ù Ø§ÙØ±ÙØ² Ø§ÙÙÙÙÙ ÙÙ 6 Ø£Ø±ÙØ§Ù Ø§ÙÙØ±Ø³Ù Ø¥ÙÙ Ø¨Ø±ÙØ¯Ù",
    "enter_email": "Ø£Ø¯Ø®Ù Ø¨Ø±ÙØ¯Ù Ø§ÙØ¥ÙÙØªØ±ÙÙÙ",
    "enter_email_for_code": "Ø£Ø¯Ø®Ù Ø¨Ø±ÙØ¯Ù Ø§ÙØ¥ÙÙØªØ±ÙÙÙ ÙØ§Ø³ØªÙØ§Ù Ø±ÙØ² Ø§ÙØªØ­ÙÙ",
    "enter_new_password": "Ø£Ø¯Ø®Ù ÙÙÙØ© Ø§ÙÙØ±ÙØ± Ø§ÙØ¬Ø¯ÙØ¯Ø©",
    "enter_password": "Ø£Ø¯Ø®Ù ÙÙÙØ© Ø§ÙÙØ±ÙØ±",
    "enter_verify_code": "Ø£Ø¯Ø®Ù Ø±ÙØ² Ø§ÙØªØ­ÙÙ",
    "error": "Ø®Ø·Ø£",
    "error_network": "Ø®Ø·Ø£ ÙÙ Ø§ÙØ´Ø¨ÙØ©. ØªØ­ÙÙ ÙÙ Ø§ØªØµØ§ÙÙ ÙØ­Ø§ÙÙ ÙØ±Ø© Ø£Ø®Ø±Ù.",
    "error_request_failed": "ÙØ´Ù Ø§ÙØ·ÙØ¨. Ø­Ø§ÙÙ ÙØ±Ø© Ø£Ø®Ø±Ù ÙØ§Ø­ÙØ§Ù.",
    "error_timeout": "Ø§ÙØªÙØª ÙÙÙØ© Ø§ÙØ·ÙØ¨. Ø­Ø§ÙÙ ÙØ±Ø© Ø£Ø®Ø±Ù.",
    "failed_to_load": "ÙØ´Ù Ø§ÙØªØ­ÙÙÙ",
    "failed_to_load_posts": "ÙØ´Ù ØªØ­ÙÙÙ Ø§ÙÙÙØ´ÙØ±Ø§Øª",
    "failed_to_reset_password": "ÙØ´Ù Ø¥Ø¹Ø§Ø¯Ø© ØªØ¹ÙÙÙ ÙÙÙØ© Ø§ÙÙØ±ÙØ±",
    "failed_to_send_code": "ÙØ´Ù Ø¥Ø±Ø³Ø§Ù Ø§ÙØ±ÙØ²",
    "failed_to_verify": "ÙØ´Ù Ø§ÙØªØ­ÙÙ",
    "filter": "ØªØµÙÙØ©",
    "friends_count": "Ø£ØµØ¯ÙØ§Ø¡",
    "friends_referred": "Ø§ÙØ£ØµØ¯ÙØ§Ø¡ Ø§ÙÙØ¯Ø¹ÙÙÙ",
    "github": "GitHub",
    "github_connect_description": "ÙÙ Ø¨ØªÙØµÙÙ Ø­Ø³Ø§Ø¨ GitHub Ø§ÙØ®Ø§Øµ Ø¨Ù ÙØ§Ø³ØªÙØ±Ø§Ø¯ Ø§ÙÙØ³ØªÙØ¯Ø¹Ø§Øª",
    "github_integration": "ØªÙØ§ÙÙ GitHub",
    "help_support": "Ø§ÙÙØ³Ø§Ø¹Ø¯Ø© ÙØ§ÙØ¯Ø¹Ù",
    "help_support_subtitle": "Ø§Ø­ØµÙ Ø¹ÙÙ Ø§ÙÙØ³Ø§Ø¹Ø¯Ø© ÙØ§ÙØ¯Ø¹Ù",
    "import_action": "Ø§Ø³ØªÙØ±Ø§Ø¯",
    "import_dialog_description": "Ø£Ø¯Ø®Ù ÙØ¹ÙÙÙØ§Øª Ø§ÙÙØ³ØªÙØ¯Ø¹ Ø§ÙØ°Ù ØªØ±ÙØ¯ Ø§Ø³ØªÙØ±Ø§Ø¯Ù",
    "import_dialog_title": "Ø§Ø³ØªÙØ±Ø§Ø¯ ÙØ³ØªÙØ¯Ø¹ Ø¹Ø§Ù",
    "import_failed": "ÙØ´Ù Ø§Ø³ØªÙØ±Ø§Ø¯ Ø§ÙÙØ³ØªÙØ¯Ø¹",
    "import_repository": "Ø§Ø³ØªÙØ±Ø§Ø¯ ÙØ³ØªÙØ¯Ø¹",
    "import_subtitle": "Ø§Ø³ØªÙØ±Ø§Ø¯ ÙØ³ØªÙØ¯Ø¹ Ø¹Ø§Ù",
    "import_success": "ØªÙ Ø§Ø³ØªÙØ±Ø§Ø¯ Ø§ÙÙØ³ØªÙØ¯Ø¹ Ø¨ÙØ¬Ø§Ø­",
    "importing": "Ø¬Ø§Ø±Ù Ø§ÙØ§Ø³ØªÙØ±Ø§Ø¯...",
    "industry": "Ø§ÙØµÙØ§Ø¹Ø©",
    "input_error_owner_repo": "ÙØ±Ø¬Ù Ø¥Ø¯Ø®Ø§Ù Ø§Ø³Ù Ø§ÙÙØ§ÙÙ ÙØ§ÙÙØ³ØªÙØ¯Ø¹",
    "invite_code_copied": "ØªÙ ÙØ³Ø® Ø±ÙØ² Ø§ÙØ¯Ø¹ÙØ© Ø¥ÙÙ Ø§ÙØ­Ø§ÙØ¸Ø©",
    "invite_code_unavailable": "Ø±ÙØ² Ø§ÙØ¯Ø¹ÙØ© ØºÙØ± ÙØªØ§Ø­",
    "invite_description": "ÙÙ Ø¨Ø¯Ø¹ÙØ© Ø§ÙØ£ØµØ¯ÙØ§Ø¡ ÙÙØ§ÙØ¶ÙØ§Ù Ø¥ÙÙ d1v.ai ÙØ§Ø­ØµÙ Ø¹ÙÙ ÙÙØ§ÙØ¢Øª",
    "invite_friends": "Ø¯Ø¹ÙØ© Ø§ÙØ£ØµØ¯ÙØ§Ø¡",
    "invites": "Ø§ÙØ¯Ø¹ÙØ§Øª",
    "just_now": "Ø§ÙØ¢Ù",
    "language": "Ø§ÙÙØºØ©",
    "legend_less": "أقل",
    "legend_more": "أكثر",
    "light_mode": "Ø§ÙÙØ¶Ø¹ Ø§ÙÙØ§ØªØ­",
    "loading": "Ø¬Ø§Ø±Ù Ø§ÙØªØ­ÙÙÙ...",
    "login": "ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ",
    "login_failed": "ÙØ´Ù ÙÙ ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ",
    "login_first": "ÙØ±Ø¬Ù ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ Ø£ÙÙØ§Ù",
    "login_required_button": "ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ",
    "login_required_create_post_message": "ØªØ­ØªØ§Ø¬ Ø¥ÙÙ ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ ÙØ¥ÙØ´Ø§Ø¡ ÙÙØ´ÙØ±.",
    "login_required_dashboard_message": "ØªØ­ØªØ§Ø¬ Ø¥ÙÙ ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ ÙØ¹Ø±Ø¶ ÙØ´Ø§Ø±ÙØ¹Ù.",
    "login_required_github_message": "ØªØ­ØªØ§Ø¬ Ø¥ÙÙ ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ ÙØ¥Ø¯Ø§Ø±Ø© ØªÙØ§ÙÙ GitHub.",
    "login_required_invites_message": "ØªØ­ØªØ§Ø¬ Ø¥ÙÙ ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ ÙØ¹Ø±Ø¶ Ø§ÙØ¯Ø¹ÙØ§Øª ÙØ§ÙÙÙØ§ÙØ¢Øª.",
    "login_required_orders_message": "ØªØ­ØªØ§Ø¬ Ø¥ÙÙ ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ ÙØ¹Ø±Ø¶ Ø§ÙØ·ÙØ¨Ø§Øª ÙØ§ÙÙÙØªØ±Ø©.",
    "login_required_settings_message": "ØªØ­ØªØ§Ø¬ Ø¥ÙÙ ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ ÙØ¥Ø¯Ø§Ø±Ø© Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø­Ø³Ø§Ø¨Ù.",
    "login_required_title": "ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ ÙØ·ÙÙØ¨",
    "login_success": "ØªÙ ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ Ø¨ÙØ¬Ø§Ø­",
    "login_with_code": "ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ Ø¨Ø§ÙØ±ÙØ²",
    "login_with_password": "ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ Ø¨ÙÙÙØ© Ø§ÙÙØ±ÙØ±",
    "logout": "ØªØ³Ø¬ÙÙ Ø§ÙØ®Ø±ÙØ¬",
    "my_invites": "Ø¯Ø¹ÙØ§ØªÙ",
    "my_invites_subtitle": "Ø¹Ø±Ø¶ Ø³Ø¬Ù Ø§ÙØ¯Ø¹ÙØ§Øª Ø§ÙØ®Ø§Øµ Ø¨Ù",
    "new_password": "ÙÙÙØ© Ø§ÙÙØ±ÙØ± Ø§ÙØ¬Ø¯ÙØ¯Ø©",
    "no_posts_yet": "ÙØ§ ØªÙØ¬Ø¯ ÙÙØ´ÙØ±Ø§Øª Ø¨Ø¹Ø¯",
    "notifications": "Ø§ÙØ¥Ø´Ø¹Ø§Ø±Ø§Øª",
    "notifications_subtitle": "Ø¥Ø¯Ø§Ø±Ø© Ø§ÙØ¥Ø´Ø¹Ø§Ø±Ø§Øª",
    "other": "Ø£Ø®Ø±Ù",
    "owner_hint": "Ø§Ø³Ù Ø§ÙÙØ³ØªØ®Ø¯Ù Ø£Ù Ø§ÙÙÙØ¸ÙØ©",
    "owner_label": "Ø§ÙÙØ§ÙÙ",
    "password": "ÙÙÙØ© Ø§ÙÙØ±ÙØ±",
    "password_length_error": "ÙØ¬Ø¨ Ø£Ù ØªÙÙÙ ÙÙÙØ© Ø§ÙÙØ±ÙØ± 6 Ø£Ø­Ø±Ù Ø¹ÙÙ Ø§ÙØ£ÙÙ",
    "password_required": "ÙØ±Ø¬Ù Ø¥Ø¯Ø®Ø§Ù ÙÙÙØ© Ø§ÙÙØ±ÙØ±",
    "password_reset_success": "ØªÙ Ø¥Ø¹Ø§Ø¯Ø© ØªØ¹ÙÙÙ ÙÙÙØ© Ø§ÙÙØ±ÙØ± Ø¨ÙØ¬Ø§Ø­",
    "passwords_do_not_match": "ÙÙÙØ§Øª Ø§ÙÙØ±ÙØ± ØºÙØ± ÙØªØ·Ø§Ø¨ÙØ©",
    "pricing": "Ø§ÙØªØ³Ø¹ÙØ±",
    "privacy": "Ø§ÙØ®ØµÙØµÙØ©",
    "profile": "Ø§ÙÙÙÙ Ø§ÙØ´Ø®ØµÙ",
    "project_name_hint": "Ø§ØªØ±ÙÙ ÙØ§Ø±ØºÙØ§ ÙØ§Ø³ØªØ®Ø¯Ø§Ù Ø§Ø³Ù Ø§ÙÙØ³ØªÙØ¯Ø¹",
    "project_name_optional": "Ø§Ø³Ù Ø§ÙÙØ´Ø±ÙØ¹ (Ø§Ø®ØªÙØ§Ø±Ù)",
    "prompt_activity_title": "نشاط البرومبت",
    "prompt_activity_total": "الإجمالي:",
    "prompts_unit": "برومبت",
    "re_enter_new_password": "Ø£Ø¹Ø¯ Ø¥Ø¯Ø®Ø§Ù ÙÙÙØ© Ø§ÙÙØ±ÙØ± Ø§ÙØ¬Ø¯ÙØ¯Ø©",
    "recent_projects": "Ø§ÙÙØ´Ø§Ø±ÙØ¹ Ø§ÙØ£Ø®ÙØ±Ø©",
    "refresh": "ØªØ­Ø¯ÙØ«",
    "repo_hint": "Ø§Ø³Ù-Ø§ÙÙØ³ØªÙØ¯Ø¹",
    "repo_label": "Ø§ÙÙØ³ØªÙØ¯Ø¹",
    "resend_after": "Ø¥Ø¹Ø§Ø¯Ø© Ø§ÙØ¥Ø±Ø³Ø§Ù Ø¨Ø¹Ø¯",
    "resend_code": "Ø¥Ø¹Ø§Ø¯Ø© Ø¥Ø±Ø³Ø§Ù Ø§ÙØ±ÙØ²",
    "reset_password": "Ø¥Ø¹Ø§Ø¯Ø© ØªØ¹ÙÙÙ ÙÙÙØ© Ø§ÙÙØ±ÙØ±",
    "reset_password_subtitle": "Ø¥Ø¹Ø§Ø¯Ø© ØªØ¹ÙÙÙ ÙÙÙØ© ÙØ±ÙØ± ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ",
    "resetting": "Ø¬Ø§Ø±Ù Ø¥Ø¹Ø§Ø¯Ø© Ø§ÙØªØ¹ÙÙÙ...",
    "retry": "Ø¥Ø¹Ø§Ø¯Ø© Ø§ÙÙØ­Ø§ÙÙØ©",
    "save": "Ø­ÙØ¸",
    "save_changes": "Ø­ÙØ¸ Ø§ÙØªØºÙÙØ±Ø§Øª",
    "search": "Ø¨Ø­Ø«",
    "send_code": "Ø¥Ø±Ø³Ø§Ù Ø§ÙØ±ÙØ²",
    "sending": "Ø¬Ø§Ø±Ù Ø§ÙØ¥Ø±Ø³Ø§Ù...",
    "session_expired_message": "Ø§ÙØªÙØª ØµÙØ§Ø­ÙØ© ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ. ÙØ±Ø¬Ù ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ ÙØ±Ø© Ø£Ø®Ø±Ù.",
    "session_expired_title": "Ø§ÙØªÙØª Ø§ÙØ¬ÙØ³Ø©",
    "settings": "Ø§ÙØ¥Ø¹Ø¯Ø§Ø¯Ø§Øª",
    "share_failed": "ÙØ´Ù Ø§ÙÙØ´Ø§Ø±ÙØ©",
    "share_invite_code": "ÙØ´Ø§Ø±ÙØ© Ø±ÙØ² Ø§ÙØ¯Ø¹ÙØ©",
    "share_message_subject": "Ø§ÙØ¶Ù Ø¥ÙÙ ÙÙ d1v.ai",
    "share_success": "ØªÙ ÙØ´Ø§Ø±ÙØ© Ø±ÙØ² Ø§ÙØ¯Ø¹ÙØ© Ø¨ÙØ¬Ø§Ø­",
    "sort": "ØªØ±ØªÙØ¨",
    "success": "ÙØ¬Ø§Ø­",
    "sync_failed": "ÙØ´Ù ÙØ²Ø§ÙÙØ© Ø§ÙÙØ³ØªÙØ¯Ø¹Ø§Øª",
    "sync_repositories": "ÙØ²Ø§ÙÙØ© Ø§ÙÙØ³ØªÙØ¯Ø¹Ø§Øª",
    "sync_subtitle": "ØªØ­Ø¯ÙØ« ÙØ§Ø¦ÙØ© Ø§ÙÙØ³ØªÙØ¯Ø¹Ø§Øª Ø§ÙØ®Ø§ØµØ© Ø¨Ù",
    "sync_success": "ØªÙØª ÙØ²Ø§ÙÙØ© Ø§ÙÙØ³ØªÙØ¯Ø¹Ø§Øª Ø¨ÙØ¬Ø§Ø­",
    "syncing": "Ø¬Ø§Ø±Ù Ø§ÙÙØ²Ø§ÙÙØ©",
    "syncing_message": "Ø¬Ø§Ø±Ù ÙØ²Ø§ÙÙØ© Ø§ÙÙØ³ØªÙØ¯Ø¹Ø§Øª...",
    "system_mode": "Ø§ÙÙØ¸Ø§Ù",
    "theme_subtitle": "Ø§ÙÙØ¶Ø¹ Ø§ÙÙØ§ØªØ­ Ø£Ù Ø§ÙØ¯Ø§ÙÙ",
    "theme_switched": "ØªÙ Ø§ÙØªØ¨Ø¯ÙÙ Ø¥ÙÙ",
    "theme_title": "Ø§ÙÙØ¸ÙØ±",
    "theme_updated": "ØªÙ ØªØ­Ø¯ÙØ« Ø§ÙÙØ¸ÙØ±",
    "verify_code": "Ø±ÙØ² Ø§ÙØªØ­ÙÙ",
    "verify_code_complete": "ÙØ±Ø¬Ù Ø¥Ø¯Ø®Ø§Ù Ø±ÙØ² Ø§ÙØªØ­ÙÙ ÙØ§ÙÙØ§Ù",
    "verify_code_required": "ÙØ±Ø¬Ù Ø¥Ø¯Ø®Ø§Ù Ø±ÙØ² Ø§ÙØªØ­ÙÙ",
    "verify_login": "Ø§ÙØªØ­ÙÙ ÙØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ",
    "verifying": "Ø¬Ø§Ø±Ù Ø§ÙØªØ­ÙÙ...",
    "wallet_addresses": "Ø¹ÙØ§ÙÙÙ Ø§ÙÙØ­ÙØ¸Ø©",
    "welcome": "ÙØ±Ø­Ø¨Ø§Ù",
    "your_invite_code": "Ø±ÙØ² Ø§ÙØ¯Ø¹ÙØ© Ø§ÙØ®Ø§Øµ Ø¨Ù",
  },
  "en": <String, String>{
    "about": "About",
    "about_description": "An AI-powered app development platform.",
    "about_subtitle": "App version and info",
    "about_title": "About",
    "activity": "Activity",
    "agree_terms": "By logging in, you agree to our Terms of Service and Privacy Policy",
    "api_settings": "API",
    "appearance": "Appearance",
    "basic_information": "Basic Information",
    "be_first_to_share": "Be the first to share something!",
    "bind_email": "Bind Email",
    "bind_email_subtitle": "Bind email to your account",
    "cancel": "Cancel",
    "choose_theme": "Choose Theme",
    "code_sent_success": "Verification code sent successfully",
    "code_sent_to": "Verification code sent to",
    "community": "Community",
    "company_name": "Company Name",
    "company_website": "Company Website",
    "confirm": "Confirm",
    "confirm_password": "Confirm Password",
    "connect_github": "Connect GitHub",
    "contact_support": "Contact Support",
    "copied": "Copied",
    "create_project": "Create Project",
    "dark_mode": "Dark Mode",
    "dashboard": "Dashboard",
    "delete": "Delete",
    "docs": "Docs",
    "edit": "Edit",
    "edit_profile": "Edit Profile",
    "email": "Email",
    "email_address": "Email Address",
    "email_bound_success": "Email bound successfully",
    "email_invalid": "Please enter a valid email address",
    "email_required": "Please enter email address",
    "enter_code_and_new_password": "Enter the verification code and your new password",
    "enter_code_sent": "Enter the 6-digit verification code sent to your email",
    "enter_email": "Enter your email",
    "enter_email_for_code": "Enter your email address to receive a verification code",
    "enter_new_password": "Enter new password",
    "enter_password": "Enter password",
    "enter_verify_code": "Enter verification code",
    "error": "Error",
    "error_network": "Network error. Please check your connection and try again.",
    "error_request_failed": "Request failed. Please try again later.",
    "error_timeout": "Request timed out. Please try again.",
    "failed_to_load": "Failed to load",
    "failed_to_load_posts": "Failed to load posts",
    "failed_to_reset_password": "Failed to reset password",
    "failed_to_send_code": "Failed to send verification code",
    "failed_to_verify": "Failed to verify code",
    "filter": "Filter",
    "friends_count": "friends",
    "friends_referred": "Friends Referred",
    "github": "GitHub",
    "github_connect_description": "Connect your GitHub account to import repositories",
    "github_integration": "GitHub Integration",
    "help_support": "Help & Support",
    "help_support_subtitle": "Get help and support",
    "import_action": "Import",
    "import_dialog_description": "Enter the repository information you want to import",
    "import_dialog_title": "Import Public Repository",
    "import_failed": "Failed to import repository",
    "import_repository": "Import Repository",
    "import_subtitle": "Import a public repository",
    "import_success": "Repository imported successfully",
    "importing": "Importing...",
    "industry": "Industry",
    "input_error_owner_repo": "Please enter owner and repository name",
    "invite_code_copied": "Invite code copied to clipboard",
    "invite_code_unavailable": "Invite code not available",
    "invite_description": "Invite friends to join d1v.ai and get rewards",
    "invite_friends": "Invite Friends",
    "invites": "Invites",
    "just_now": "Just now",
    "language": "Language",
    "legend_less": "Less",
    "legend_more": "More",
    "light_mode": "Light Mode",
    "loading": "Loading...",
    "login": "Login",
    "login_failed": "Login failed",
    "login_first": "Please login first",
    "login_required_button": "Login",
    "login_required_create_post_message": "You need to log in to create a post.",
    "login_required_dashboard_message": "You need to log in to view your projects.",
    "login_required_github_message": "You need to log in to manage GitHub integration.",
    "login_required_invites_message": "You need to log in to view invites and rewards.",
    "login_required_orders_message": "You need to log in to view orders and billing.",
    "login_required_settings_message": "You need to log in to manage your account settings.",
    "login_required_title": "Login required",
    "login_success": "Login successful",
    "login_with_code": "Login with Code",
    "login_with_password": "Login with Password",
    "logout": "Logout",
    "my_invites": "My Invites",
    "my_invites_subtitle": "View your invitation history",
    "new_password": "New Password",
    "no_posts_yet": "No posts yet",
    "notifications": "Notifications",
    "notifications_subtitle": "Manage notifications",
    "other": "Other",
    "owner_hint": "username or organization",
    "owner_label": "Owner",
    "password": "Password",
    "password_length_error": "Password must be at least 6 characters",
    "password_required": "Please enter password",
    "password_reset_success": "Password reset successfully",
    "passwords_do_not_match": "Passwords do not match",
    "pricing": "Pricing",
    "privacy": "Privacy",
    "profile": "Profile",
    "project_name_hint": "Leave empty to use repository name",
    "project_name_optional": "Project Name (Optional)",
    "prompt_activity_title": "Prompt activity",
    "prompt_activity_total": "Total:",
    "prompts_unit": "prompts",
    "re_enter_new_password": "Re-enter new password",
    "recent_projects": "Recent Projects",
    "refresh": "Refresh",
    "repo_hint": "repository-name",
    "repo_label": "Repository",
    "resend_after": "Resend after",
    "resend_code": "Resend Code",
    "reset_password": "Reset Password",
    "reset_password_subtitle": "Reset your login password",
    "resetting": "Resetting...",
    "retry": "Retry",
    "save": "Save",
    "save_changes": "Save Changes",
    "search": "Search",
    "send_code": "Send Code",
    "sending": "Sending...",
    "session_expired_message": "Your login has expired. Please log in again.",
    "session_expired_title": "Session expired",
    "settings": "Settings",
    "share_failed": "Failed to share",
    "share_invite_code": "Share Invite Code",
    "share_message_subject": "Join me on d1v.ai",
    "share_success": "Invite code shared successfully",
    "sort": "Sort",
    "success": "Success",
    "sync_failed": "Failed to sync repositories",
    "sync_repositories": "Sync Repositories",
    "sync_subtitle": "Update your repository list",
    "sync_success": "Repositories synced successfully",
    "syncing": "Syncing",
    "syncing_message": "Syncing repositories...",
    "system_mode": "System",
    "theme_subtitle": "Light or Dark mode",
    "theme_switched": "Switched to",
    "theme_title": "Theme",
    "theme_updated": "Theme Updated",
    "verify_code": "Verification Code",
    "verify_code_complete": "Please enter complete verification code",
    "verify_code_required": "Please enter verification code",
    "verify_login": "Verify Login",
    "verifying": "Verifying...",
    "wallet_addresses": "Wallet Addresses",
    "welcome": "Welcome",
    "your_invite_code": "Your Invite Code",
  },
  "es": <String, String>{
    "about": "Acerca de",
    "about_description": "Una plataforma de desarrollo de aplicaciones impulsada por IA.",
    "about_subtitle": "VersiÃ³n e informaciÃ³n de la aplicaciÃ³n",
    "about_title": "Acerca de",
    "activity": "Actividad",
    "agree_terms": "Al iniciar sesiÃ³n, acepta nuestros TÃ©rminos de Servicio y PolÃ­tica de Privacidad",
    "api_settings": "API",
    "appearance": "Apariencia",
    "basic_information": "InformaciÃ³n bÃ¡sica",
    "be_first_to_share": "Â¡SÃ© el primero en compartir algo!",
    "bind_email": "Vincular correo",
    "bind_email_subtitle": "Vincular correo a su cuenta",
    "cancel": "Cancelar",
    "choose_theme": "Elegir tema",
    "code_sent_success": "CÃ³digo enviado exitosamente",
    "code_sent_to": "CÃ³digo enviado a",
    "community": "Comunidad",
    "company_name": "Nombre de la empresa",
    "company_website": "Sitio web de la empresa",
    "confirm": "Confirmar",
    "confirm_password": "Confirmar contraseÃ±a",
    "connect_github": "Conectar GitHub",
    "contact_support": "Contactar soporte",
    "copied": "Copiado",
    "create_project": "Crear proyecto",
    "dark_mode": "Modo oscuro",
    "dashboard": "Panel",
    "delete": "Eliminar",
    "docs": "Documentos",
    "edit": "Editar",
    "edit_profile": "Editar perfil",
    "email": "Correo electrÃ³nico",
    "email_address": "DirecciÃ³n de correo",
    "email_bound_success": "Correo electrÃ³nico vinculado exitosamente",
    "email_invalid": "Por favor ingrese un correo electrÃ³nico vÃ¡lido",
    "email_required": "Por favor ingrese su correo electrÃ³nico",
    "enter_code_and_new_password": "Ingrese el cÃ³digo y la nueva contraseÃ±a",
    "enter_code_sent": "Ingrese el cÃ³digo de 6 dÃ­gitos enviado a su correo",
    "enter_email": "Ingrese su correo electrÃ³nico",
    "enter_email_for_code": "Ingrese su correo para recibir un cÃ³digo de verificaciÃ³n",
    "enter_new_password": "Ingrese la nueva contraseÃ±a",
    "enter_password": "Ingrese la contraseÃ±a",
    "enter_verify_code": "Ingrese el cÃ³digo de verificaciÃ³n",
    "error": "Error",
    "error_network": "Error de red. Comprueba tu conexiÃ³n e intÃ©ntalo de nuevo.",
    "error_request_failed": "La solicitud fallÃ³. IntÃ©ntalo mÃ¡s tarde.",
    "error_timeout": "Tiempo de espera agotado. IntÃ©ntalo de nuevo.",
    "failed_to_load": "Error al cargar",
    "failed_to_load_posts": "Error al cargar publicaciones",
    "failed_to_reset_password": "Error al restablecer contraseÃ±a",
    "failed_to_send_code": "Error al enviar cÃ³digo",
    "failed_to_verify": "Error al verificar",
    "filter": "Filtrar",
    "friends_count": "amigos",
    "friends_referred": "Amigos referidos",
    "github": "GitHub",
    "github_connect_description": "Conecte su cuenta de GitHub para importar repositorios",
    "github_integration": "IntegraciÃ³n con GitHub",
    "help_support": "Ayuda y soporte",
    "help_support_subtitle": "Obtener ayuda y soporte",
    "import_action": "Importar",
    "import_dialog_description": "Ingrese la informaciÃ³n del repositorio que desea importar",
    "import_dialog_title": "Importar Repositorio PÃºblico",
    "import_failed": "Error al importar repositorio",
    "import_repository": "Importar repositorio",
    "import_subtitle": "Importar un repositorio pÃºblico",
    "import_success": "Repositorio importado exitosamente",
    "importing": "Importando...",
    "industry": "Industria",
    "input_error_owner_repo": "Por favor ingrese el propietario y el nombre del repositorio",
    "invite_code_copied": "CÃ³digo de invitaciÃ³n copiado al portapapeles",
    "invite_code_unavailable": "CÃ³digo de invitaciÃ³n no disponible",
    "invite_description": "Invite a amigos a unirse a d1v.ai y obtenga recompensas",
    "invite_friends": "Invitar amigos",
    "invites": "Invitaciones",
    "just_now": "Justo ahora",
    "language": "Idioma",
    "legend_less": "Menos",
    "legend_more": "Más",
    "light_mode": "Modo claro",
    "loading": "Cargando...",
    "login": "Iniciar sesiÃ³n",
    "login_failed": "Error al iniciar sesiÃ³n",
    "login_first": "Por favor inicie sesiÃ³n primero",
    "login_required_button": "Iniciar sesiÃ³n",
    "login_required_create_post_message": "Necesitas iniciar sesiÃ³n para crear una publicaciÃ³n.",
    "login_required_dashboard_message": "Necesitas iniciar sesiÃ³n para ver tus proyectos.",
    "login_required_github_message": "Necesitas iniciar sesiÃ³n para administrar la integraciÃ³n con GitHub.",
    "login_required_invites_message": "Necesitas iniciar sesiÃ³n para ver invitaciones y recompensas.",
    "login_required_orders_message": "Necesitas iniciar sesiÃ³n para ver pedidos y facturaciÃ³n.",
    "login_required_settings_message": "Necesitas iniciar sesiÃ³n para administrar la configuraciÃ³n de tu cuenta.",
    "login_required_title": "Inicio de sesiÃ³n requerido",
    "login_success": "Inicio de sesiÃ³n exitoso",
    "login_with_code": "Iniciar sesiÃ³n con cÃ³digo",
    "login_with_password": "Iniciar sesiÃ³n con contraseÃ±a",
    "logout": "Cerrar sesiÃ³n",
    "my_invites": "Mis invitaciones",
    "my_invites_subtitle": "Ver su historial de invitaciones",
    "new_password": "Nueva contraseÃ±a",
    "no_posts_yet": "AÃºn no hay publicaciones",
    "notifications": "Notificaciones",
    "notifications_subtitle": "Administrar notificaciones",
    "other": "Otro",
    "owner_hint": "usuario u organizaciÃ³n",
    "owner_label": "Propietario",
    "password": "ContraseÃ±a",
    "password_length_error": "La contraseÃ±a debe tener al menos 6 caracteres",
    "password_required": "Por favor ingrese la contraseÃ±a",
    "password_reset_success": "ContraseÃ±a restablecida exitosamente",
    "passwords_do_not_match": "Las contraseÃ±as no coinciden",
    "pricing": "Precios",
    "privacy": "Privacidad",
    "profile": "Perfil",
    "project_name_hint": "Dejar vacÃ­o para usar el nombre del repositorio",
    "project_name_optional": "Nombre del proyecto (Opcional)",
    "prompt_activity_title": "Actividad de prompts",
    "prompt_activity_total": "Total:",
    "prompts_unit": "prompts",
    "re_enter_new_password": "Reingrese la nueva contraseÃ±a",
    "recent_projects": "Proyectos recientes",
    "refresh": "Actualizar",
    "repo_hint": "nombre-del-repositorio",
    "repo_label": "Repositorio",
    "resend_after": "Reenviar despuÃ©s de",
    "resend_code": "Reenviar cÃ³digo",
    "reset_password": "Restablecer contraseÃ±a",
    "reset_password_subtitle": "Restablecer su contraseÃ±a",
    "resetting": "Restableciendo...",
    "retry": "Reintentar",
    "save": "Guardar",
    "save_changes": "Guardar cambios",
    "search": "Buscar",
    "send_code": "Enviar cÃ³digo",
    "sending": "Enviando...",
    "session_expired_message": "Tu sesiÃ³n ha caducado. Inicia sesiÃ³n de nuevo.",
    "session_expired_title": "SesiÃ³n caducada",
    "settings": "ConfiguraciÃ³n",
    "share_failed": "Error al compartir",
    "share_invite_code": "Compartir cÃ³digo de invitaciÃ³n",
    "share_message_subject": "Ãnete a mÃ­ en d1v.ai",
    "share_success": "CÃ³digo de invitaciÃ³n compartido exitosamente",
    "sort": "Ordenar",
    "success": "Ãxito",
    "sync_failed": "Error al sincronizar repositorios",
    "sync_repositories": "Sincronizar repositorios",
    "sync_subtitle": "Actualizar su lista de repositorios",
    "sync_success": "Repositorios sincronizados exitosamente",
    "syncing": "Sincronizando",
    "syncing_message": "Sincronizando repositorios...",
    "system_mode": "Sistema",
    "theme_subtitle": "Modo claro u oscuro",
    "theme_switched": "Cambiado a",
    "theme_title": "Tema",
    "theme_updated": "Tema actualizado",
    "verify_code": "CÃ³digo de verificaciÃ³n",
    "verify_code_complete": "Por favor ingrese el cÃ³digo de verificaciÃ³n completo",
    "verify_code_required": "Por favor ingrese el cÃ³digo de verificaciÃ³n",
    "verify_login": "Verificar inicio de sesiÃ³n",
    "verifying": "Verificando...",
    "wallet_addresses": "Direcciones de billetera",
    "welcome": "Bienvenido",
    "your_invite_code": "Su cÃ³digo de invitaciÃ³n",
  },
  "fr": <String, String>{
    "about": "Ã propos",
    "about_description": "Une plateforme de dÃ©veloppement d'applications alimentÃ©e par l'IA.",
    "about_subtitle": "Version de l'application et informations",
    "about_title": "Ã propos",
    "activity": "ActivitÃ©",
    "agree_terms": "En vous connectant, vous acceptez nos Conditions de Service et notre Politique de ConfidentialitÃ©",
    "api_settings": "API",
    "appearance": "Apparence",
    "basic_information": "Informations de base",
    "be_first_to_share": "Soyez le premier Ã  partager quelque chose!",
    "bind_email": "Lier l'e-mail",
    "bind_email_subtitle": "Lier l'e-mail Ã  votre compte",
    "cancel": "Annuler",
    "choose_theme": "Choisir le thÃ¨me",
    "code_sent_success": "Code envoyÃ© avec succÃ¨s",
    "code_sent_to": "Code envoyÃ© Ã ",
    "community": "CommunautÃ©",
    "company_name": "Nom de l'entreprise",
    "company_website": "Site web de l'entreprise",
    "confirm": "Confirmer",
    "confirm_password": "Confirmer le mot de passe",
    "connect_github": "Connecter GitHub",
    "contact_support": "Contacter le support",
    "copied": "CopiÃ©",
    "create_project": "CrÃ©er un projet",
    "dark_mode": "Mode sombre",
    "dashboard": "Tableau de bord",
    "delete": "Supprimer",
    "docs": "Documents",
    "edit": "Modifier",
    "edit_profile": "Modifier le profil",
    "email": "E-mail",
    "email_address": "Adresse e-mail",
    "email_bound_success": "E-mail liÃ© avec succÃ¨s",
    "email_invalid": "Veuillez entrer une adresse e-mail valide",
    "email_required": "Veuillez entrer votre adresse e-mail",
    "enter_code_and_new_password": "Entrez le code de vÃ©rification et votre nouveau mot de passe",
    "enter_code_sent": "Entrez le code de vÃ©rification Ã  6 chiffres envoyÃ© Ã  votre e-mail",
    "enter_email": "Entrez votre e-mail",
    "enter_email_for_code": "Entrez votre adresse e-mail pour recevoir un code de vÃ©rification",
    "enter_new_password": "Entrez le nouveau mot de passe",
    "enter_password": "Entrez le mot de passe",
    "enter_verify_code": "Entrez le code de vÃ©rification",
    "error": "Erreur",
    "error_network": "Erreur rÃ©seau. VÃ©rifiez votre connexion et rÃ©essayez.",
    "error_request_failed": "La requÃªte a Ã©chouÃ©. Veuillez rÃ©essayer plus tard.",
    "error_timeout": "DÃ©lai dâattente dÃ©passÃ©. Veuillez rÃ©essayer.",
    "failed_to_load": "Ãchec du chargement",
    "failed_to_load_posts": "Ãchec du chargement des publications",
    "failed_to_reset_password": "Ãchec de la rÃ©initialisation du mot de passe",
    "failed_to_send_code": "Ãchec de l'envoi du code",
    "failed_to_verify": "Ãchec de la vÃ©rification",
    "filter": "Filtrer",
    "friends_count": "amis",
    "friends_referred": "Amis parrainÃ©s",
    "github": "GitHub",
    "github_connect_description": "Connectez votre compte GitHub pour importer des rÃ©fÃ©rentiels",
    "github_integration": "IntÃ©gration GitHub",
    "help_support": "Aide et support",
    "help_support_subtitle": "Obtenir de l'aide et du support",
    "import_action": "Importer",
    "import_dialog_description": "Entrez les informations du rÃ©fÃ©rentiel que vous souhaitez importer",
    "import_dialog_title": "Importer un rÃ©fÃ©rentiel public",
    "import_failed": "Ãchec de l'importation du rÃ©fÃ©rentiel",
    "import_repository": "Importer un rÃ©fÃ©rentiel",
    "import_subtitle": "Importer un rÃ©fÃ©rentiel public",
    "import_success": "RÃ©fÃ©rentiel importÃ© avec succÃ¨s",
    "importing": "Importation...",
    "industry": "Industrie",
    "input_error_owner_repo": "Veuillez entrer le propriÃ©taire et le nom du rÃ©fÃ©rentiel",
    "invite_code_copied": "Code d'invitation copiÃ© dans le presse-papiers",
    "invite_code_unavailable": "Code d'invitation non disponible",
    "invite_description": "Invitez des amis Ã  rejoindre d1v.ai et obtenez des rÃ©compenses",
    "invite_friends": "Inviter des amis",
    "invites": "Invitations",
    "just_now": "Ã l'instant",
    "language": "Langue",
    "legend_less": "Moins",
    "legend_more": "Plus",
    "light_mode": "Mode clair",
    "loading": "Chargement...",
    "login": "Se connecter",
    "login_failed": "Ãchec de la connexion",
    "login_first": "Veuillez d'abord vous connecter",
    "login_required_button": "Se connecter",
    "login_required_create_post_message": "Vous devez vous connecter pour crÃ©er une publication.",
    "login_required_dashboard_message": "Vous devez vous connecter pour voir vos projets.",
    "login_required_github_message": "Vous devez vous connecter pour gÃ©rer lâintÃ©gration GitHub.",
    "login_required_invites_message": "Vous devez vous connecter pour voir les invitations et les rÃ©compenses.",
    "login_required_orders_message": "Vous devez vous connecter pour voir les commandes et la facturation.",
    "login_required_settings_message": "Vous devez vous connecter pour gÃ©rer les paramÃ¨tres de votre compte.",
    "login_required_title": "Connexion requise",
    "login_success": "Connexion rÃ©ussie",
    "login_with_code": "Se connecter avec code",
    "login_with_password": "Se connecter avec mot de passe",
    "logout": "Se dÃ©connecter",
    "my_invites": "Mes invitations",
    "my_invites_subtitle": "Voir votre historique d'invitations",
    "new_password": "Nouveau mot de passe",
    "no_posts_yet": "Pas encore de publications",
    "notifications": "Notifications",
    "notifications_subtitle": "GÃ©rer les notifications",
    "other": "Autre",
    "owner_hint": "nom d'utilisateur ou organisation",
    "owner_label": "PropriÃ©taire",
    "password": "Mot de passe",
    "password_length_error": "Le mot de passe doit comporter au moins 6 caractÃ¨res",
    "password_required": "Veuillez entrer le mot de passe",
    "password_reset_success": "Mot de passe rÃ©initialisÃ© avec succÃ¨s",
    "passwords_do_not_match": "Les mots de passe ne correspondent pas",
    "pricing": "Tarification",
    "privacy": "ConfidentialitÃ©",
    "profile": "Profil",
    "project_name_hint": "Laisser vide pour utiliser le nom du rÃ©fÃ©rentiel",
    "project_name_optional": "Nom du projet (Facultatif)",
    "prompt_activity_title": "Activité des prompts",
    "prompt_activity_total": "Total :",
    "prompts_unit": "prompts",
    "re_enter_new_password": "Entrez Ã  nouveau le nouveau mot de passe",
    "recent_projects": "Projets rÃ©cents",
    "refresh": "Actualiser",
    "repo_hint": "nom-du-rÃ©fÃ©rentiel",
    "repo_label": "RÃ©fÃ©rentiel",
    "resend_after": "Renvoyer aprÃ¨s",
    "resend_code": "Renvoyer le code",
    "reset_password": "RÃ©initialiser le mot de passe",
    "reset_password_subtitle": "RÃ©initialiser votre mot de passe de connexion",
    "resetting": "RÃ©initialisation...",
    "retry": "RÃ©essayer",
    "save": "Enregistrer",
    "save_changes": "Enregistrer les modifications",
    "search": "Rechercher",
    "send_code": "Envoyer le code",
    "sending": "Envoi...",
    "session_expired_message": "Votre session a expirÃ©. Veuillez vous reconnecter.",
    "session_expired_title": "Session expirÃ©e",
    "settings": "ParamÃ¨tres",
    "share_failed": "Ãchec du partage",
    "share_invite_code": "Partager le code d'invitation",
    "share_message_subject": "Rejoignez-moi sur d1v.ai",
    "share_success": "Code d'invitation partagÃ© avec succÃ¨s",
    "sort": "Trier",
    "success": "SuccÃ¨s",
    "sync_failed": "Ãchec de la synchronisation des rÃ©fÃ©rentiels",
    "sync_repositories": "Synchroniser les rÃ©fÃ©rentiels",
    "sync_subtitle": "Mettre Ã  jour votre liste de rÃ©fÃ©rentiels",
    "sync_success": "RÃ©fÃ©rentiels synchronisÃ©s avec succÃ¨s",
    "syncing": "Synchronisation",
    "syncing_message": "Synchronisation des rÃ©fÃ©rentiels...",
    "system_mode": "SystÃ¨me",
    "theme_subtitle": "Mode clair ou sombre",
    "theme_switched": "PassÃ© Ã ",
    "theme_title": "ThÃ¨me",
    "theme_updated": "ThÃ¨me mis Ã  jour",
    "verify_code": "Code de vÃ©rification",
    "verify_code_complete": "Veuillez entrer le code de vÃ©rification complet",
    "verify_code_required": "Veuillez entrer le code de vÃ©rification",
    "verify_login": "VÃ©rifier la connexion",
    "verifying": "VÃ©rification...",
    "wallet_addresses": "Adresses de portefeuille",
    "welcome": "Bienvenue",
    "your_invite_code": "Votre code d'invitation",
  },
  "ja": <String, String>{
    "about": "ãã®ã¢ããªã«ã¤ãã¦",
    "about_description": "AIãæ´»ç¨ããã¢ããªéçºãã©ãããã©ã¼ã ã",
    "about_subtitle": "ã¢ããªã®ãã¼ã¸ã§ã³ã¨æå ±",
    "about_title": "ã¢ããªæå ±",
    "activity": "ã¢ã¯ãã£ããã£",
    "agree_terms": "ã­ã°ã¤ã³ãããã¨ã§ãå©ç¨è¦ç´ã¨ãã©ã¤ãã·ã¼ã«åæãããã¨ã«ãªãã¾ã",
    "api_settings": "API",
    "appearance": "å¤è¦³",
    "basic_information": "åºæ¬æå ±",
    "be_first_to_share": "æåã®æç¨¿èã«ãªãã¾ãããï¼",
    "bind_email": "ã¡ã¼ã«ã¢ãã¬ã¹ããã¤ã³ã",
    "bind_email_subtitle": "ã¢ã«ã¦ã³ãã«ã¡ã¼ã«ã¢ãã¬ã¹ããã¤ã³ã",
    "cancel": "ã­ã£ã³ã»ã«",
    "choose_theme": "ãã¼ããé¸æ",
    "code_sent_success": "ã³ã¼ããæ­£å¸¸ã«éä¿¡ããã¾ãã",
    "code_sent_to": "éä¿¡å:",
    "community": "ã³ãã¥ããã£",
    "company_name": "ä¼ç¤¾å",
    "company_website": "ä¼ç¤¾ã®ã¦ã§ããµã¤ã",
    "confirm": "ç¢ºèª",
    "confirm_password": "ãã¹ã¯ã¼ãã®ç¢ºèª",
    "connect_github": "GitHub ã«æ¥ç¶",
    "contact_support": "ãµãã¼ãã«é£çµ¡",
    "copied": "ã³ãã¼ãã¾ãã",
    "create_project": "ãã­ã¸ã§ã¯ããä½æ",
    "dark_mode": "ãã¼ã¯ã¢ã¼ã",
    "dashboard": "ããã·ã¥ãã¼ã",
    "delete": "åé¤",
    "docs": "ãã­ã¥ã¡ã³ã",
    "edit": "ç·¨é",
    "edit_profile": "ãã­ãã£ã¼ã«ãç·¨é",
    "email": "ã¡ã¼ã«ã¢ãã¬ã¹",
    "email_address": "ã¡ã¼ã«ã¢ãã¬ã¹",
    "email_bound_success": "ã¡ã¼ã«ã¢ãã¬ã¹ã®ãã¤ã³ãã«æåãã¾ãã",
    "email_invalid": "æå¹ãªã¡ã¼ã«ã¢ãã¬ã¹ãå¥åãã¦ãã ãã",
    "email_required": "ã¡ã¼ã«ã¢ãã¬ã¹ãå¥åãã¦ãã ãã",
    "enter_code_and_new_password": "èªè¨¼ã³ã¼ãã¨æ°ãããã¹ã¯ã¼ããå¥åãã¦ãã ãã",
    "enter_code_sent": "ã¡ã¼ã«ã«éä¿¡ããã6æ¡ã®èªè¨¼ã³ã¼ããå¥åãã¦ãã ãã",
    "enter_email": "ã¡ã¼ã«ã¢ãã¬ã¹ãå¥åãã¦ãã ãã",
    "enter_email_for_code": "èªè¨¼ã³ã¼ããåãåãã¡ã¼ã«ã¢ãã¬ã¹ãå¥åãã¦ãã ãã",
    "enter_new_password": "æ°ãããã¹ã¯ã¼ããå¥åãã¦ãã ãã",
    "enter_password": "ãã¹ã¯ã¼ããå¥åãã¦ãã ãã",
    "enter_verify_code": "èªè¨¼ã³ã¼ããå¥åãã¦ãã ãã",
    "error": "ã¨ã©ã¼",
    "error_network": "ãããã¯ã¼ã¯ã¨ã©ã¼ã§ããæ¥ç¶ãç¢ºèªãã¦åè©¦è¡ãã¦ãã ããã",
    "error_request_failed": "ãªã¯ã¨ã¹ãã«å¤±æãã¾ããããã°ãããã¦ããåè©¦è¡ãã¦ãã ããã",
    "error_timeout": "ã¿ã¤ã ã¢ã¦ããã¾ãããããä¸åº¦ãè©¦ããã ããã",
    "failed_to_load": "èª­ã¿è¾¼ã¿ã«å¤±æãã¾ãã",
    "failed_to_load_posts": "æç¨¿ã®èª­ã¿è¾¼ã¿ã«å¤±æãã¾ãã",
    "failed_to_reset_password": "ãã¹ã¯ã¼ãã®ãªã»ããã«å¤±æãã¾ãã",
    "failed_to_send_code": "ã³ã¼ãã®éä¿¡ã«å¤±æãã¾ãã",
    "failed_to_verify": "èªè¨¼ã«å¤±æãã¾ãã",
    "filter": "ãã£ã«ã¿ã¼",
    "friends_count": "äººã®åé",
    "friends_referred": "æå¾ããåé",
    "github": "GitHub",
    "github_connect_description": "GitHub ã¢ã«ã¦ã³ããæ¥ç¶ãã¦ãªãã¸ããªãã¤ã³ãã¼ã",
    "github_integration": "GitHub é£æº",
    "help_support": "ãã«ãï¼ãµãã¼ã",
    "help_support_subtitle": "ãã«ãã¨ãµãã¼ããåãã",
    "import_action": "ã¤ã³ãã¼ã",
    "import_dialog_description": "ã¤ã³ãã¼ãããããªãã¸ããªæå ±ãå¥åãã¦ãã ãã",
    "import_dialog_title": "å¬éãªãã¸ããªãã¤ã³ãã¼ã",
    "import_failed": "ãªãã¸ããªã®ã¤ã³ãã¼ãã«å¤±æãã¾ãã",
    "import_repository": "ãªãã¸ããªãã¤ã³ãã¼ã",
    "import_subtitle": "å¬éãªãã¸ããªãã¤ã³ãã¼ã",
    "import_success": "ãªãã¸ããªãæ­£å¸¸ã«ã¤ã³ãã¼ãããã¾ãã",
    "importing": "ã¤ã³ãã¼ãä¸­...",
    "industry": "æ¥­ç¨®",
    "input_error_owner_repo": "ãªã¼ãã¼ã¨ãªãã¸ããªåãå¥åãã¦ãã ãã",
    "invite_code_copied": "æå¾ã³ã¼ããã¯ãªãããã¼ãã«ã³ãã¼ãã¾ãã",
    "invite_code_unavailable": "æå¾ã³ã¼ãã¯å©ç¨ã§ãã¾ãã",
    "invite_description": "åéã d1v.ai ã«æå¾ãã¦å ±é¬ãç²å¾",
    "invite_friends": "åéãæå¾",
    "invites": "æå¾",
    "just_now": "ãã£ãä»",
    "language": "è¨èª",
    "legend_less": "少ない",
    "legend_more": "多い",
    "light_mode": "ã©ã¤ãã¢ã¼ã",
    "loading": "èª­ã¿è¾¼ã¿ä¸­...",
    "login": "ã­ã°ã¤ã³",
    "login_failed": "ã­ã°ã¤ã³ã«å¤±æãã¾ãã",
    "login_first": "åã«ã­ã°ã¤ã³ãã¦ãã ãã",
    "login_required_button": "ã­ã°ã¤ã³",
    "login_required_create_post_message": "æç¨¿ãä½æããã«ã¯ã­ã°ã¤ã³ãã¦ãã ããã",
    "login_required_dashboard_message": "ãã­ã¸ã§ã¯ããè¡¨ç¤ºããã«ã¯ã­ã°ã¤ã³ãã¦ãã ããã",
    "login_required_github_message": "GitHub é£æºãç®¡çããã«ã¯ã­ã°ã¤ã³ãã¦ãã ããã",
    "login_required_invites_message": "æå¾ã¨å ±é¬ãè¡¨ç¤ºããã«ã¯ã­ã°ã¤ã³ãã¦ãã ããã",
    "login_required_orders_message": "æ³¨æã¨è«æ±æå ±ãè¡¨ç¤ºããã«ã¯ã­ã°ã¤ã³ãã¦ãã ããã",
    "login_required_settings_message": "ã¢ã«ã¦ã³ãè¨­å®ãç®¡çããã«ã¯ã­ã°ã¤ã³ãã¦ãã ããã",
    "login_required_title": "ã­ã°ã¤ã³ãå¿è¦ã§ã",
    "login_success": "ã­ã°ã¤ã³ãã¾ãã",
    "login_with_code": "ã³ã¼ãã§ã­ã°ã¤ã³",
    "login_with_password": "ãã¹ã¯ã¼ãã§ã­ã°ã¤ã³",
    "logout": "ã­ã°ã¢ã¦ã",
    "my_invites": "æå¾å±¥æ­´",
    "my_invites_subtitle": "æå¾å±¥æ­´ãè¡¨ç¤º",
    "new_password": "æ°ãããã¹ã¯ã¼ã",
    "no_posts_yet": "ã¾ã æç¨¿ãããã¾ãã",
    "notifications": "éç¥",
    "notifications_subtitle": "éç¥ãç®¡ç",
    "other": "ãã®ä»",
    "owner_hint": "ã¦ã¼ã¶ã¼åã¾ãã¯çµç¹å",
    "owner_label": "ãªã¼ãã¼",
    "password": "ãã¹ã¯ã¼ã",
    "password_length_error": "ãã¹ã¯ã¼ãã¯6æå­ä»¥ä¸ã§ããå¿è¦ãããã¾ã",
    "password_required": "ãã¹ã¯ã¼ããå¥åãã¦ãã ãã",
    "password_reset_success": "ãã¹ã¯ã¼ãã®ãªã»ããã«æåãã¾ãã",
    "passwords_do_not_match": "ãã¹ã¯ã¼ããä¸è´ãã¾ãã",
    "pricing": "æé",
    "privacy": "ãã©ã¤ãã·ã¼",
    "profile": "ãã­ãã£ã¼ã«",
    "project_name_hint": "ç©ºæ¬ã®å ´åããªãã¸ããªåãä½¿ç¨",
    "project_name_optional": "ãã­ã¸ã§ã¯ãå (ä»»æ)",
    "prompt_activity_title": "プロンプトのアクティビティ",
    "prompt_activity_total": "合計:",
    "prompts_unit": "件",
    "re_enter_new_password": "æ°ãããã¹ã¯ã¼ããåå¥åãã¦ãã ãã",
    "recent_projects": "æè¿ã®ãã­ã¸ã§ã¯ã",
    "refresh": "æ´æ°",
    "repo_hint": "ãªãã¸ããªå",
    "repo_label": "ãªãã¸ããª",
    "resend_after": "åéä¿¡ã¾ã§",
    "resend_code": "ã³ã¼ããåéä¿¡",
    "reset_password": "ãã¹ã¯ã¼ãããªã»ãã",
    "reset_password_subtitle": "ã­ã°ã¤ã³ãã¹ã¯ã¼ãããªã»ãã",
    "resetting": "ãªã»ããä¸­...",
    "retry": "åè©¦è¡",
    "save": "ä¿å­",
    "save_changes": "å¤æ´ãä¿å­",
    "search": "æ¤ç´¢",
    "send_code": "ã³ã¼ããéä¿¡",
    "sending": "éä¿¡ä¸­...",
    "session_expired_message": "ã­ã°ã¤ã³ã®æå¹æéãåãã¾ãããååº¦ã­ã°ã¤ã³ãã¦ãã ããã",
    "session_expired_title": "ã»ãã·ã§ã³ã®æå¹æéåã",
    "settings": "è¨­å®",
    "share_failed": "ã·ã§ã¢ã«å¤±æãã¾ãã",
    "share_invite_code": "æå¾ã³ã¼ããã·ã§ã¢",
    "share_message_subject": "d1v.ai ã«åå ããã",
    "share_success": "æå¾ã³ã¼ããæ­£å¸¸ã«ã·ã§ã¢ããã¾ãã",
    "sort": "ä¸¦ã¹æ¿ã",
    "success": "æå",
    "sync_failed": "ãªãã¸ããªã®åæã«å¤±æãã¾ãã",
    "sync_repositories": "ãªãã¸ããªãåæ",
    "sync_subtitle": "ãªãã¸ããªãªã¹ããæ´æ°",
    "sync_success": "ãªãã¸ããªãæ­£å¸¸ã«åæããã¾ãã",
    "syncing": "åæä¸­",
    "syncing_message": "ãªãã¸ããªãåæä¸­...",
    "system_mode": "ã·ã¹ãã ",
    "theme_subtitle": "ã©ã¤ãã¢ã¼ãã¾ãã¯ãã¼ã¯ã¢ã¼ã",
    "theme_switched": "æ¬¡ã¸åãæ¿ãã¾ãã:",
    "theme_title": "ãã¼ã",
    "theme_updated": "ãã¼ããæ´æ°ããã¾ãã",
    "verify_code": "èªè¨¼ã³ã¼ã",
    "verify_code_complete": "å®å¨ãªèªè¨¼ã³ã¼ããå¥åãã¦ãã ãã",
    "verify_code_required": "èªè¨¼ã³ã¼ããå¥åãã¦ãã ãã",
    "verify_login": "ã­ã°ã¤ã³ãèªè¨¼",
    "verifying": "èªè¨¼ä¸­...",
    "wallet_addresses": "ã¦ã©ã¬ããã¢ãã¬ã¹",
    "welcome": "ãããã",
    "your_invite_code": "æå¾ã³ã¼ã",
  },
  "ru": <String, String>{
    "about": "Ð Ð¿ÑÐ¾Ð³ÑÐ°Ð¼Ð¼Ðµ",
    "about_description": "ÐÐ»Ð°ÑÑÐ¾ÑÐ¼Ð° Ð´Ð»Ñ ÑÐ°Ð·ÑÐ°Ð±Ð¾ÑÐºÐ¸ Ð¿ÑÐ¸Ð»Ð¾Ð¶ÐµÐ½Ð¸Ð¹ Ñ Ð¸ÑÐ¿Ð¾Ð»ÑÐ·Ð¾Ð²Ð°Ð½Ð¸ÐµÐ¼ ÐÐ.",
    "about_subtitle": "ÐÐµÑÑÐ¸Ñ Ð¿ÑÐ¸Ð»Ð¾Ð¶ÐµÐ½Ð¸Ñ Ð¸ Ð¸Ð½ÑÐ¾ÑÐ¼Ð°ÑÐ¸Ñ",
    "about_title": "Ð Ð¿ÑÐ¸Ð»Ð¾Ð¶ÐµÐ½Ð¸Ð¸",
    "activity": "ÐÐºÑÐ¸Ð²Ð½Ð¾ÑÑÑ",
    "agree_terms": "ÐÑÐ¾Ð´Ñ Ð² ÑÐ¸ÑÑÐµÐ¼Ñ, Ð²Ñ ÑÐ¾Ð³Ð»Ð°ÑÐ°ÐµÑÐµÑÑ Ñ Ð½Ð°ÑÐ¸Ð¼Ð¸ Ð£ÑÐ»Ð¾Ð²Ð¸ÑÐ¼Ð¸ Ð¾Ð±ÑÐ»ÑÐ¶Ð¸Ð²Ð°Ð½Ð¸Ñ Ð¸ ÐÐ¾Ð»Ð¸ÑÐ¸ÐºÐ¾Ð¹ ÐºÐ¾Ð½ÑÐ¸Ð´ÐµÐ½ÑÐ¸Ð°Ð»ÑÐ½Ð¾ÑÑÐ¸",
    "api_settings": "API",
    "appearance": "ÐÐ½ÐµÑÐ½Ð¸Ð¹ Ð²Ð¸Ð´",
    "basic_information": "ÐÑÐ½Ð¾Ð²Ð½Ð°Ñ Ð¸Ð½ÑÐ¾ÑÐ¼Ð°ÑÐ¸Ñ",
    "be_first_to_share": "ÐÑÐ´ÑÑÐµ Ð¿ÐµÑÐ²ÑÐ¼, ÐºÑÐ¾ Ð¿Ð¾Ð´ÐµÐ»Ð¸ÑÑÑ ÑÐµÐ¼-ÑÐ¾!",
    "bind_email": "ÐÑÐ¸Ð²ÑÐ·Ð°ÑÑ Ð¿Ð¾ÑÑÑ",
    "bind_email_subtitle": "ÐÑÐ¸Ð²ÑÐ·Ð°ÑÑ Ð¿Ð¾ÑÑÑ Ðº Ð°ÐºÐºÐ°ÑÐ½ÑÑ",
    "cancel": "ÐÑÐ¼ÐµÐ½Ð°",
    "choose_theme": "ÐÑÐ±ÑÐ°ÑÑ ÑÐµÐ¼Ñ",
    "code_sent_success": "ÐÐ¾Ð´ ÑÑÐ¿ÐµÑÐ½Ð¾ Ð¾ÑÐ¿ÑÐ°Ð²Ð»ÐµÐ½",
    "code_sent_to": "ÐÐ¾Ð´ Ð¾ÑÐ¿ÑÐ°Ð²Ð»ÐµÐ½ Ð½Ð°",
    "community": "Ð¡Ð¾Ð¾Ð±ÑÐµÑÑÐ²Ð¾",
    "company_name": "ÐÐ°Ð·Ð²Ð°Ð½Ð¸Ðµ ÐºÐ¾Ð¼Ð¿Ð°Ð½Ð¸Ð¸",
    "company_website": "ÐÐµÐ±-ÑÐ°Ð¹Ñ ÐºÐ¾Ð¼Ð¿Ð°Ð½Ð¸Ð¸",
    "confirm": "ÐÐ¾Ð´ÑÐ²ÐµÑÐ´Ð¸ÑÑ",
    "confirm_password": "ÐÐ¾Ð´ÑÐ²ÐµÑÐ´Ð¸ÑÑ Ð¿Ð°ÑÐ¾Ð»Ñ",
    "connect_github": "ÐÐ¾Ð´ÐºÐ»ÑÑÐ¸ÑÑ GitHub",
    "contact_support": "Ð¡Ð²ÑÐ·Ð°ÑÑÑÑ Ñ Ð¿Ð¾Ð´Ð´ÐµÑÐ¶ÐºÐ¾Ð¹",
    "copied": "Ð¡ÐºÐ¾Ð¿Ð¸ÑÐ¾Ð²Ð°Ð½Ð¾",
    "create_project": "Ð¡Ð¾Ð·Ð´Ð°ÑÑ Ð¿ÑÐ¾ÐµÐºÑ",
    "dark_mode": "Ð¢ÐµÐ¼Ð½Ð°Ñ ÑÐµÐ¼Ð°",
    "dashboard": "ÐÐ°Ð½ÐµÐ»Ñ ÑÐ¿ÑÐ°Ð²Ð»ÐµÐ½Ð¸Ñ",
    "delete": "Ð£Ð´Ð°Ð»Ð¸ÑÑ",
    "docs": "ÐÐ¾ÐºÑÐ¼ÐµÐ½ÑÑ",
    "edit": "Ð ÐµÐ´Ð°ÐºÑÐ¸ÑÐ¾Ð²Ð°ÑÑ",
    "edit_profile": "Ð ÐµÐ´Ð°ÐºÑÐ¸ÑÐ¾Ð²Ð°ÑÑ Ð¿ÑÐ¾ÑÐ¸Ð»Ñ",
    "email": "Ð­Ð»ÐµÐºÑÑÐ¾Ð½Ð½Ð°Ñ Ð¿Ð¾ÑÑÐ°",
    "email_address": "ÐÐ´ÑÐµÑ ÑÐ»ÐµÐºÑÑÐ¾Ð½Ð½Ð¾Ð¹ Ð¿Ð¾ÑÑÑ",
    "email_bound_success": "Ð­Ð»ÐµÐºÑÑÐ¾Ð½Ð½Ð°Ñ Ð¿Ð¾ÑÑÐ° ÑÑÐ¿ÐµÑÐ½Ð¾ Ð¿ÑÐ¸Ð²ÑÐ·Ð°Ð½Ð°",
    "email_invalid": "ÐÐ¾Ð¶Ð°Ð»ÑÐ¹ÑÑÐ°, Ð²Ð²ÐµÐ´Ð¸ÑÐµ Ð´ÐµÐ¹ÑÑÐ²Ð¸ÑÐµÐ»ÑÐ½ÑÐ¹ Ð°Ð´ÑÐµÑ ÑÐ»ÐµÐºÑÑÐ¾Ð½Ð½Ð¾Ð¹ Ð¿Ð¾ÑÑÑ",
    "email_required": "ÐÐ¾Ð¶Ð°Ð»ÑÐ¹ÑÑÐ°, Ð²Ð²ÐµÐ´Ð¸ÑÐµ Ð°Ð´ÑÐµÑ ÑÐ»ÐµÐºÑÑÐ¾Ð½Ð½Ð¾Ð¹ Ð¿Ð¾ÑÑÑ",
    "enter_code_and_new_password": "ÐÐ²ÐµÐ´Ð¸ÑÐµ ÐºÐ¾Ð´ Ð¿Ð¾Ð´ÑÐ²ÐµÑÐ¶Ð´ÐµÐ½Ð¸Ñ Ð¸ Ð½Ð¾Ð²ÑÐ¹ Ð¿Ð°ÑÐ¾Ð»Ñ",
    "enter_code_sent": "ÐÐ²ÐµÐ´Ð¸ÑÐµ 6-Ð·Ð½Ð°ÑÐ½ÑÐ¹ ÐºÐ¾Ð´ Ð¿Ð¾Ð´ÑÐ²ÐµÑÐ¶Ð´ÐµÐ½Ð¸Ñ, Ð¾ÑÐ¿ÑÐ°Ð²Ð»ÐµÐ½Ð½ÑÐ¹ Ð½Ð° Ð²Ð°ÑÑ Ð¿Ð¾ÑÑÑ",
    "enter_email": "ÐÐ²ÐµÐ´Ð¸ÑÐµ Ð²Ð°ÑÑ Ð¿Ð¾ÑÑÑ",
    "enter_email_for_code": "ÐÐ²ÐµÐ´Ð¸ÑÐµ Ð°Ð´ÑÐµÑ ÑÐ»ÐµÐºÑÑÐ¾Ð½Ð½Ð¾Ð¹ Ð¿Ð¾ÑÑÑ Ð´Ð»Ñ Ð¿Ð¾Ð»ÑÑÐµÐ½Ð¸Ñ ÐºÐ¾Ð´Ð° Ð¿Ð¾Ð´ÑÐ²ÐµÑÐ¶Ð´ÐµÐ½Ð¸Ñ",
    "enter_new_password": "ÐÐ²ÐµÐ´Ð¸ÑÐµ Ð½Ð¾Ð²ÑÐ¹ Ð¿Ð°ÑÐ¾Ð»Ñ",
    "enter_password": "ÐÐ²ÐµÐ´Ð¸ÑÐµ Ð¿Ð°ÑÐ¾Ð»Ñ",
    "enter_verify_code": "ÐÐ²ÐµÐ´Ð¸ÑÐµ ÐºÐ¾Ð´ Ð¿Ð¾Ð´ÑÐ²ÐµÑÐ¶Ð´ÐµÐ½Ð¸Ñ",
    "error": "ÐÑÐ¸Ð±ÐºÐ°",
    "error_network": "ÐÑÐ¸Ð±ÐºÐ° ÑÐµÑÐ¸. ÐÑÐ¾Ð²ÐµÑÑÑÐµ Ð¿Ð¾Ð´ÐºÐ»ÑÑÐµÐ½Ð¸Ðµ Ð¸ Ð¿Ð¾Ð¿ÑÐ¾Ð±ÑÐ¹ÑÐµ ÑÐ½Ð¾Ð²Ð°.",
    "error_request_failed": "ÐÐ°Ð¿ÑÐ¾Ñ Ð½Ðµ ÑÐ´Ð°Ð»ÑÑ. ÐÐ¾Ð¶Ð°Ð»ÑÐ¹ÑÑÐ°, Ð¿Ð¾Ð¿ÑÐ¾Ð±ÑÐ¹ÑÐµ Ð¿Ð¾Ð·Ð¶Ðµ.",
    "error_timeout": "ÐÑÐµÐ¼Ñ Ð¾Ð¶Ð¸Ð´Ð°Ð½Ð¸Ñ Ð¸ÑÑÐµÐºÐ»Ð¾. ÐÐ¾Ð¿ÑÐ¾Ð±ÑÐ¹ÑÐµ ÑÐ½Ð¾Ð²Ð°.",
    "failed_to_load": "ÐÐµ ÑÐ´Ð°Ð»Ð¾ÑÑ Ð·Ð°Ð³ÑÑÐ·Ð¸ÑÑ",
    "failed_to_load_posts": "ÐÐµ ÑÐ´Ð°Ð»Ð¾ÑÑ Ð·Ð°Ð³ÑÑÐ·Ð¸ÑÑ Ð¿ÑÐ±Ð»Ð¸ÐºÐ°ÑÐ¸Ð¸",
    "failed_to_reset_password": "ÐÐµ ÑÐ´Ð°Ð»Ð¾ÑÑ ÑÐ±ÑÐ¾ÑÐ¸ÑÑ Ð¿Ð°ÑÐ¾Ð»Ñ",
    "failed_to_send_code": "ÐÐµ ÑÐ´Ð°Ð»Ð¾ÑÑ Ð¾ÑÐ¿ÑÐ°Ð²Ð¸ÑÑ ÐºÐ¾Ð´",
    "failed_to_verify": "ÐÐµ ÑÐ´Ð°Ð»Ð¾ÑÑ Ð¿ÑÐ¾Ð²ÐµÑÐ¸ÑÑ",
    "filter": "Ð¤Ð¸Ð»ÑÑÑ",
    "friends_count": "Ð´ÑÑÐ·ÐµÐ¹",
    "friends_referred": "ÐÑÐ¸Ð³Ð»Ð°ÑÐµÐ½Ð½ÑÐµ Ð´ÑÑÐ·ÑÑ",
    "github": "GitHub",
    "github_connect_description": "ÐÐ¾Ð´ÐºÐ»ÑÑÐ¸ÑÐµ ÑÐ²Ð¾Ð¹ Ð°ÐºÐºÐ°ÑÐ½Ñ GitHub Ð´Ð»Ñ Ð¸Ð¼Ð¿Ð¾ÑÑÐ° ÑÐµÐ¿Ð¾Ð·Ð¸ÑÐ¾ÑÐ¸ÐµÐ²",
    "github_integration": "ÐÐ½ÑÐµÐ³ÑÐ°ÑÐ¸Ñ Ñ GitHub",
    "help_support": "ÐÐ¾Ð¼Ð¾ÑÑ Ð¸ Ð¿Ð¾Ð´Ð´ÐµÑÐ¶ÐºÐ°",
    "help_support_subtitle": "ÐÐ¾Ð»ÑÑÐ¸ÑÑ Ð¿Ð¾Ð¼Ð¾ÑÑ Ð¸ Ð¿Ð¾Ð´Ð´ÐµÑÐ¶ÐºÑ",
    "import_action": "ÐÐ¼Ð¿Ð¾ÑÑÐ¸ÑÐ¾Ð²Ð°ÑÑ",
    "import_dialog_description": "ÐÐ²ÐµÐ´Ð¸ÑÐµ Ð¸Ð½ÑÐ¾ÑÐ¼Ð°ÑÐ¸Ñ Ð¾ ÑÐµÐ¿Ð¾Ð·Ð¸ÑÐ¾ÑÐ¸Ð¸, ÐºÐ¾ÑÐ¾ÑÑÐ¹ ÑÐ¾ÑÐ¸ÑÐµ Ð¸Ð¼Ð¿Ð¾ÑÑÐ¸ÑÐ¾Ð²Ð°ÑÑ",
    "import_dialog_title": "ÐÐ¼Ð¿Ð¾ÑÑ Ð¿ÑÐ±Ð»Ð¸ÑÐ½Ð¾Ð³Ð¾ ÑÐµÐ¿Ð¾Ð·Ð¸ÑÐ¾ÑÐ¸Ñ",
    "import_failed": "ÐÐµ ÑÐ´Ð°Ð»Ð¾ÑÑ Ð¸Ð¼Ð¿Ð¾ÑÑÐ¸ÑÐ¾Ð²Ð°ÑÑ ÑÐµÐ¿Ð¾Ð·Ð¸ÑÐ¾ÑÐ¸Ð¹",
    "import_repository": "ÐÐ¼Ð¿Ð¾ÑÑÐ¸ÑÐ¾Ð²Ð°ÑÑ ÑÐµÐ¿Ð¾Ð·Ð¸ÑÐ¾ÑÐ¸Ð¹",
    "import_subtitle": "ÐÐ¼Ð¿Ð¾ÑÑÐ¸ÑÐ¾Ð²Ð°ÑÑ Ð¿ÑÐ±Ð»Ð¸ÑÐ½ÑÐ¹ ÑÐµÐ¿Ð¾Ð·Ð¸ÑÐ¾ÑÐ¸Ð¹",
    "import_success": "Ð ÐµÐ¿Ð¾Ð·Ð¸ÑÐ¾ÑÐ¸Ð¹ ÑÑÐ¿ÐµÑÐ½Ð¾ Ð¸Ð¼Ð¿Ð¾ÑÑÐ¸ÑÐ¾Ð²Ð°Ð½",
    "importing": "ÐÐ¼Ð¿Ð¾ÑÑ...",
    "industry": "ÐÑÑÐ°ÑÐ»Ñ",
    "input_error_owner_repo": "ÐÐ¾Ð¶Ð°Ð»ÑÐ¹ÑÑÐ°, Ð²Ð²ÐµÐ´Ð¸ÑÐµ Ð²Ð»Ð°Ð´ÐµÐ»ÑÑÐ° Ð¸ Ð½Ð°Ð·Ð²Ð°Ð½Ð¸Ðµ ÑÐµÐ¿Ð¾Ð·Ð¸ÑÐ¾ÑÐ¸Ñ",
    "invite_code_copied": "ÐÐ¾Ð´ Ð¿ÑÐ¸Ð³Ð»Ð°ÑÐµÐ½Ð¸Ñ ÑÐºÐ¾Ð¿Ð¸ÑÐ¾Ð²Ð°Ð½ Ð² Ð±ÑÑÐµÑ Ð¾Ð±Ð¼ÐµÐ½Ð°",
    "invite_code_unavailable": "ÐÐ¾Ð´ Ð¿ÑÐ¸Ð³Ð»Ð°ÑÐµÐ½Ð¸Ñ Ð½ÐµÐ´Ð¾ÑÑÑÐ¿ÐµÐ½",
    "invite_description": "ÐÑÐ¸Ð³Ð»Ð°ÑÐ°Ð¹ÑÐµ Ð´ÑÑÐ·ÐµÐ¹ Ð¿ÑÐ¸ÑÐ¾ÐµÐ´Ð¸Ð½Ð¸ÑÑÑÑ Ðº d1v.ai Ð¸ Ð¿Ð¾Ð»ÑÑÐ°Ð¹ÑÐµ Ð½Ð°Ð³ÑÐ°Ð´Ñ",
    "invite_friends": "ÐÑÐ¸Ð³Ð»Ð°ÑÐ¸ÑÑ Ð´ÑÑÐ·ÐµÐ¹",
    "invites": "ÐÑÐ¸Ð³Ð»Ð°ÑÐµÐ½Ð¸Ñ",
    "just_now": "Ð¢Ð¾Ð»ÑÐºÐ¾ ÑÑÐ¾",
    "language": "Ð¯Ð·ÑÐº",
    "legend_less": "Меньше",
    "legend_more": "Больше",
    "light_mode": "Ð¡Ð²ÐµÑÐ»Ð°Ñ ÑÐµÐ¼Ð°",
    "loading": "ÐÐ°Ð³ÑÑÐ·ÐºÐ°...",
    "login": "ÐÐ¾Ð¹ÑÐ¸",
    "login_failed": "ÐÑÐ¸Ð±ÐºÐ° Ð²ÑÐ¾Ð´Ð°",
    "login_first": "ÐÐ¾Ð¶Ð°Ð»ÑÐ¹ÑÑÐ°, Ð²Ð¾Ð¹Ð´Ð¸ÑÐµ ÑÐ½Ð°ÑÐ°Ð»Ð°",
    "login_required_button": "ÐÐ¾Ð¹ÑÐ¸",
    "login_required_create_post_message": "Ð§ÑÐ¾Ð±Ñ ÑÐ¾Ð·Ð´Ð°ÑÑ Ð¿ÑÐ±Ð»Ð¸ÐºÐ°ÑÐ¸Ñ, Ð½ÐµÐ¾Ð±ÑÐ¾Ð´Ð¸Ð¼Ð¾ Ð²Ð¾Ð¹ÑÐ¸ Ð² ÑÐ¸ÑÑÐµÐ¼Ñ.",
    "login_required_dashboard_message": "Ð§ÑÐ¾Ð±Ñ Ð¿ÑÐ¾ÑÐ¼Ð°ÑÑÐ¸Ð²Ð°ÑÑ Ð¿ÑÐ¾ÐµÐºÑÑ, Ð½ÐµÐ¾Ð±ÑÐ¾Ð´Ð¸Ð¼Ð¾ Ð²Ð¾Ð¹ÑÐ¸ Ð² ÑÐ¸ÑÑÐµÐ¼Ñ.",
    "login_required_github_message": "Ð§ÑÐ¾Ð±Ñ ÑÐ¿ÑÐ°Ð²Ð»ÑÑÑ Ð¸Ð½ÑÐµÐ³ÑÐ°ÑÐ¸ÐµÐ¹ GitHub, Ð½ÐµÐ¾Ð±ÑÐ¾Ð´Ð¸Ð¼Ð¾ Ð²Ð¾Ð¹ÑÐ¸ Ð² ÑÐ¸ÑÑÐµÐ¼Ñ.",
    "login_required_invites_message": "Ð§ÑÐ¾Ð±Ñ Ð¿ÑÐ¾ÑÐ¼Ð°ÑÑÐ¸Ð²Ð°ÑÑ Ð¿ÑÐ¸Ð³Ð»Ð°ÑÐµÐ½Ð¸Ñ Ð¸ Ð½Ð°Ð³ÑÐ°Ð´Ñ, Ð½ÐµÐ¾Ð±ÑÐ¾Ð´Ð¸Ð¼Ð¾ Ð²Ð¾Ð¹ÑÐ¸ Ð² ÑÐ¸ÑÑÐµÐ¼Ñ.",
    "login_required_orders_message": "Ð§ÑÐ¾Ð±Ñ Ð¿ÑÐ¾ÑÐ¼Ð°ÑÑÐ¸Ð²Ð°ÑÑ Ð·Ð°ÐºÐ°Ð·Ñ Ð¸ Ð±Ð¸Ð»Ð»Ð¸Ð½Ð³, Ð½ÐµÐ¾Ð±ÑÐ¾Ð´Ð¸Ð¼Ð¾ Ð²Ð¾Ð¹ÑÐ¸ Ð² ÑÐ¸ÑÑÐµÐ¼Ñ.",
    "login_required_settings_message": "Ð§ÑÐ¾Ð±Ñ ÑÐ¿ÑÐ°Ð²Ð»ÑÑÑ Ð½Ð°ÑÑÑÐ¾Ð¹ÐºÐ°Ð¼Ð¸ Ð°ÐºÐºÐ°ÑÐ½ÑÐ°, Ð½ÐµÐ¾Ð±ÑÐ¾Ð´Ð¸Ð¼Ð¾ Ð²Ð¾Ð¹ÑÐ¸ Ð² ÑÐ¸ÑÑÐµÐ¼Ñ.",
    "login_required_title": "Ð¢ÑÐµÐ±ÑÐµÑÑÑ Ð²ÑÐ¾Ð´",
    "login_success": "Ð£ÑÐ¿ÐµÑÐ½ÑÐ¹ Ð²ÑÐ¾Ð´",
    "login_with_code": "ÐÐ¾Ð¹ÑÐ¸ Ñ ÐºÐ¾Ð´Ð¾Ð¼",
    "login_with_password": "ÐÐ¾Ð¹ÑÐ¸ Ñ Ð¿Ð°ÑÐ¾Ð»ÐµÐ¼",
    "logout": "ÐÑÐ¹ÑÐ¸",
    "my_invites": "ÐÐ¾Ð¸ Ð¿ÑÐ¸Ð³Ð»Ð°ÑÐµÐ½Ð¸Ñ",
    "my_invites_subtitle": "ÐÑÐ¾ÑÐ¼Ð¾ÑÑ Ð¸ÑÑÐ¾ÑÐ¸Ð¸ Ð¿ÑÐ¸Ð³Ð»Ð°ÑÐµÐ½Ð¸Ð¹",
    "new_password": "ÐÐ¾Ð²ÑÐ¹ Ð¿Ð°ÑÐ¾Ð»Ñ",
    "no_posts_yet": "ÐÐ¾ÐºÐ° Ð½ÐµÑ Ð¿ÑÐ±Ð»Ð¸ÐºÐ°ÑÐ¸Ð¹",
    "notifications": "Ð£Ð²ÐµÐ´Ð¾Ð¼Ð»ÐµÐ½Ð¸Ñ",
    "notifications_subtitle": "Ð£Ð¿ÑÐ°Ð²Ð»ÐµÐ½Ð¸Ðµ ÑÐ²ÐµÐ´Ð¾Ð¼Ð»ÐµÐ½Ð¸ÑÐ¼Ð¸",
    "other": "ÐÑÑÐ³Ð¾Ðµ",
    "owner_hint": "Ð¿Ð¾Ð»ÑÐ·Ð¾Ð²Ð°ÑÐµÐ»Ñ Ð¸Ð»Ð¸ Ð¾ÑÐ³Ð°Ð½Ð¸Ð·Ð°ÑÐ¸Ñ",
    "owner_label": "ÐÐ»Ð°Ð´ÐµÐ»ÐµÑ",
    "password": "ÐÐ°ÑÐ¾Ð»Ñ",
    "password_length_error": "ÐÐ°ÑÐ¾Ð»Ñ Ð´Ð¾Ð»Ð¶ÐµÐ½ ÑÐ¾Ð´ÐµÑÐ¶Ð°ÑÑ Ð½Ðµ Ð¼ÐµÐ½ÐµÐµ 6 ÑÐ¸Ð¼Ð²Ð¾Ð»Ð¾Ð²",
    "password_required": "ÐÐ¾Ð¶Ð°Ð»ÑÐ¹ÑÑÐ°, Ð²Ð²ÐµÐ´Ð¸ÑÐµ Ð¿Ð°ÑÐ¾Ð»Ñ",
    "password_reset_success": "ÐÐ°ÑÐ¾Ð»Ñ ÑÑÐ¿ÐµÑÐ½Ð¾ ÑÐ±ÑÐ¾ÑÐµÐ½",
    "passwords_do_not_match": "ÐÐ°ÑÐ¾Ð»Ð¸ Ð½Ðµ ÑÐ¾Ð²Ð¿Ð°Ð´Ð°ÑÑ",
    "pricing": "Ð¦ÐµÐ½Ñ",
    "privacy": "ÐÐ¾Ð½ÑÐ¸Ð´ÐµÐ½ÑÐ¸Ð°Ð»ÑÐ½Ð¾ÑÑÑ",
    "profile": "ÐÑÐ¾ÑÐ¸Ð»Ñ",
    "project_name_hint": "ÐÑÑÐ°Ð²ÑÑÐµ Ð¿ÑÑÑÑÐ¼, ÑÑÐ¾Ð±Ñ Ð¸ÑÐ¿Ð¾Ð»ÑÐ·Ð¾Ð²Ð°ÑÑ Ð½Ð°Ð·Ð²Ð°Ð½Ð¸Ðµ ÑÐµÐ¿Ð¾Ð·Ð¸ÑÐ¾ÑÐ¸Ñ",
    "project_name_optional": "ÐÐ°Ð·Ð²Ð°Ð½Ð¸Ðµ Ð¿ÑÐ¾ÐµÐºÑÐ° (Ð½ÐµÐ¾Ð±ÑÐ·Ð°ÑÐµÐ»ÑÐ½Ð¾)",
    "prompt_activity_title": "Активность промптов",
    "prompt_activity_total": "Итого:",
    "prompts_unit": "промптов",
    "re_enter_new_password": "ÐÐ²ÐµÐ´Ð¸ÑÐµ Ð½Ð¾Ð²ÑÐ¹ Ð¿Ð°ÑÐ¾Ð»Ñ ÐµÑÐµ ÑÐ°Ð·",
    "recent_projects": "ÐÐµÐ´Ð°Ð²Ð½Ð¸Ðµ Ð¿ÑÐ¾ÐµÐºÑÑ",
    "refresh": "ÐÐ±Ð½Ð¾Ð²Ð¸ÑÑ",
    "repo_hint": "Ð½Ð°Ð·Ð²Ð°Ð½Ð¸Ðµ-ÑÐµÐ¿Ð¾Ð·Ð¸ÑÐ¾ÑÐ¸Ñ",
    "repo_label": "Ð ÐµÐ¿Ð¾Ð·Ð¸ÑÐ¾ÑÐ¸Ð¹",
    "resend_after": "ÐÐ¾Ð²ÑÐ¾ÑÐ¸ÑÑ ÑÐµÑÐµÐ·",
    "resend_code": "ÐÐ¾Ð²ÑÐ¾ÑÐ¸ÑÑ Ð¾ÑÐ¿ÑÐ°Ð²ÐºÑ ÐºÐ¾Ð´Ð°",
    "reset_password": "Ð¡Ð±ÑÐ¾ÑÐ¸ÑÑ Ð¿Ð°ÑÐ¾Ð»Ñ",
    "reset_password_subtitle": "Ð¡Ð±ÑÐ¾ÑÐ¸ÑÑ Ð¿Ð°ÑÐ¾Ð»Ñ Ð´Ð»Ñ Ð²ÑÐ¾Ð´Ð°",
    "resetting": "Ð¡Ð±ÑÐ¾Ñ...",
    "retry": "ÐÐ¾Ð²ÑÐ¾ÑÐ¸ÑÑ",
    "save": "Ð¡Ð¾ÑÑÐ°Ð½Ð¸ÑÑ",
    "save_changes": "Ð¡Ð¾ÑÑÐ°Ð½Ð¸ÑÑ Ð¸Ð·Ð¼ÐµÐ½ÐµÐ½Ð¸Ñ",
    "search": "ÐÐ¾Ð¸ÑÐº",
    "send_code": "ÐÑÐ¿ÑÐ°Ð²Ð¸ÑÑ ÐºÐ¾Ð´",
    "sending": "ÐÑÐ¿ÑÐ°Ð²ÐºÐ°...",
    "session_expired_message": "Ð¡ÑÐ¾Ðº Ð´ÐµÐ¹ÑÑÐ²Ð¸Ñ Ð²ÑÐ¾Ð´Ð° Ð¸ÑÑÐµÐº. ÐÐ¾Ð¶Ð°Ð»ÑÐ¹ÑÑÐ°, Ð²Ð¾Ð¹Ð´Ð¸ÑÐµ ÑÐ½Ð¾Ð²Ð°.",
    "session_expired_title": "Ð¡ÐµÑÑÐ¸Ñ Ð¸ÑÑÐµÐºÐ»Ð°",
    "settings": "ÐÐ°ÑÑÑÐ¾Ð¹ÐºÐ¸",
    "share_failed": "ÐÐµ ÑÐ´Ð°Ð»Ð¾ÑÑ Ð¿Ð¾Ð´ÐµÐ»Ð¸ÑÑÑÑ",
    "share_invite_code": "ÐÐ¾Ð´ÐµÐ»Ð¸ÑÑÑÑ ÐºÐ¾Ð´Ð¾Ð¼",
    "share_message_subject": "ÐÑÐ¸ÑÐ¾ÐµÐ´Ð¸Ð½ÑÐ¹ÑÑ ÐºÐ¾ Ð¼Ð½Ðµ Ð½Ð° d1v.ai",
    "share_success": "ÐÐ¾Ð´ Ð¿ÑÐ¸Ð³Ð»Ð°ÑÐµÐ½Ð¸Ñ ÑÑÐ¿ÐµÑÐ½Ð¾ Ð¾ÑÐ¿ÑÐ°Ð²Ð»ÐµÐ½",
    "sort": "Ð¡Ð¾ÑÑÐ¸ÑÐ¾Ð²ÐºÐ°",
    "success": "Ð£ÑÐ¿ÐµÑ",
    "sync_failed": "ÐÐµ ÑÐ´Ð°Ð»Ð¾ÑÑ ÑÐ¸Ð½ÑÑÐ¾Ð½Ð¸Ð·Ð¸ÑÐ¾Ð²Ð°ÑÑ ÑÐµÐ¿Ð¾Ð·Ð¸ÑÐ¾ÑÐ¸Ð¸",
    "sync_repositories": "Ð¡Ð¸Ð½ÑÑÐ¾Ð½Ð¸Ð·Ð¸ÑÐ¾Ð²Ð°ÑÑ ÑÐµÐ¿Ð¾Ð·Ð¸ÑÐ¾ÑÐ¸Ð¸",
    "sync_subtitle": "ÐÐ±Ð½Ð¾Ð²Ð¸ÑÑ ÑÐ¿Ð¸ÑÐ¾Ðº ÑÐµÐ¿Ð¾Ð·Ð¸ÑÐ¾ÑÐ¸ÐµÐ²",
    "sync_success": "Ð ÐµÐ¿Ð¾Ð·Ð¸ÑÐ¾ÑÐ¸Ð¸ ÑÑÐ¿ÐµÑÐ½Ð¾ ÑÐ¸Ð½ÑÑÐ¾Ð½Ð¸Ð·Ð¸ÑÐ¾Ð²Ð°Ð½Ñ",
    "syncing": "Ð¡Ð¸Ð½ÑÑÐ¾Ð½Ð¸Ð·Ð°ÑÐ¸Ñ",
    "syncing_message": "Ð¡Ð¸Ð½ÑÑÐ¾Ð½Ð¸Ð·Ð°ÑÐ¸Ñ ÑÐµÐ¿Ð¾Ð·Ð¸ÑÐ¾ÑÐ¸ÐµÐ²...",
    "system_mode": "Ð¡Ð¸ÑÑÐµÐ¼Ð½Ð°Ñ",
    "theme_subtitle": "Ð¡Ð²ÐµÑÐ»ÑÐ¹ Ð¸Ð»Ð¸ ÑÐµÐ¼Ð½ÑÐ¹ ÑÐµÐ¶Ð¸Ð¼",
    "theme_switched": "ÐÐµÑÐµÐºÐ»ÑÑÐµÐ½Ð¾ Ð½Ð°",
    "theme_title": "Ð¢ÐµÐ¼Ð°",
    "theme_updated": "Ð¢ÐµÐ¼Ð° Ð¾Ð±Ð½Ð¾Ð²Ð»ÐµÐ½Ð°",
    "verify_code": "ÐÐ¾Ð´ Ð¿Ð¾Ð´ÑÐ²ÐµÑÐ¶Ð´ÐµÐ½Ð¸Ñ",
    "verify_code_complete": "ÐÐ¾Ð¶Ð°Ð»ÑÐ¹ÑÑÐ°, Ð²Ð²ÐµÐ´Ð¸ÑÐµ Ð¿Ð¾Ð»Ð½ÑÐ¹ ÐºÐ¾Ð´ Ð¿Ð¾Ð´ÑÐ²ÐµÑÐ¶Ð´ÐµÐ½Ð¸Ñ",
    "verify_code_required": "ÐÐ¾Ð¶Ð°Ð»ÑÐ¹ÑÑÐ°, Ð²Ð²ÐµÐ´Ð¸ÑÐµ ÐºÐ¾Ð´ Ð¿Ð¾Ð´ÑÐ²ÐµÑÐ¶Ð´ÐµÐ½Ð¸Ñ",
    "verify_login": "ÐÑÐ¾Ð²ÐµÑÐ¸ÑÑ Ð²ÑÐ¾Ð´",
    "verifying": "ÐÑÐ¾Ð²ÐµÑÐºÐ°...",
    "wallet_addresses": "ÐÐ´ÑÐµÑÐ° ÐºÐ¾ÑÐµÐ»ÑÐºÐ¾Ð²",
    "welcome": "ÐÐ¾Ð±ÑÐ¾ Ð¿Ð¾Ð¶Ð°Ð»Ð¾Ð²Ð°ÑÑ",
    "your_invite_code": "ÐÐ°Ñ ÐºÐ¾Ð´ Ð¿ÑÐ¸Ð³Ð»Ð°ÑÐµÐ½Ð¸Ñ",
  },
  "zh": <String, String>{
    "about": "å³äº",
    "about_description": "ä¸ä¸ª AI é©±å¨çåºç¨å¼åå¹³å°ã",
    "about_subtitle": "åºç¨çæ¬åä¿¡æ¯",
    "about_title": "å³äº",
    "activity": "å¨æ",
    "agree_terms": "ç»å½å³è¡¨ç¤ºæ¨åææä»¬çæå¡æ¡æ¬¾åéç§æ¿ç­",
    "api_settings": "API",
    "appearance": "å¤è§",
    "basic_information": "åºæ¬ä¿¡æ¯",
    "be_first_to_share": "æ¢ååå¸ç¬¬ä¸æ¡å¨æ",
    "bind_email": "ç»å®é®ç®±",
    "bind_email_subtitle": "ç»å®é®ç®±å°æ¨çè´¦æ·",
    "cancel": "åæ¶",
    "choose_theme": "éæ©ä¸»é¢",
    "code_sent_success": "éªè¯ç å·²åéï¼è¯·æ¥æ¶é®ä»¶",
    "code_sent_to": "éªè¯ç å·²åéè³",
    "community": "ç¤¾åº",
    "company_name": "å¬å¸åç§°",
    "company_website": "å¬å¸ç½ç«",
    "confirm": "ç¡®è®¤",
    "confirm_password": "ç¡®è®¤å¯ç ",
    "connect_github": "è¿æ¥ GitHub",
    "contact_support": "èç³»æ¯æ",
    "copied": "å·²å¤å¶",
    "create_project": "æ°å»ºé¡¹ç®",
    "dark_mode": "æ·±è²æ¨¡å¼",
    "dashboard": "å·¥ä½å°",
    "delete": "å é¤",
    "docs": "ææ¡£",
    "edit": "ç¼è¾",
    "edit_profile": "ç¼è¾èµæ",
    "email": "é®ç®±",
    "email_address": "é®ç®±å°å",
    "email_bound_success": "é®ç®±ç»å®æå",
    "email_invalid": "è¯·è¾å¥ææçé®ç®±å°å",
    "email_required": "è¯·è¾å¥é®ç®±å°å",
    "enter_code_and_new_password": "è¾å¥éªè¯ç åæ°å¯ç ",
    "enter_code_sent": "è¾å¥åéå°æ¨é®ç®±ç6ä½éªè¯ç ",
    "enter_email": "è¯·è¾å¥æ¨çé®ç®±",
    "enter_email_for_code": "è¾å¥é®ç®±å°åä»¥æ¥æ¶éªè¯ç ",
    "enter_new_password": "è¯·è¾å¥æ°å¯ç ",
    "enter_password": "è¯·è¾å¥å¯ç ",
    "enter_verify_code": "è¯·è¾å¥éªè¯ç ",
    "error": "éè¯¯",
    "error_network": "ç½ç»è¿æ¥å¤±è´¥ï¼è¯·æ£æ¥ç½ç»åéè¯",
    "error_request_failed": "è¯·æ±å¤±è´¥ï¼è¯·ç¨åéè¯",
    "error_timeout": "è¯·æ±è¶æ¶ï¼è¯·ç¨åéè¯",
    "failed_to_load": "å è½½å¤±è´¥",
    "failed_to_load_posts": "åå®¹å è½½å¤±è´¥",
    "failed_to_reset_password": "éç½®å¯ç å¤±è´¥",
    "failed_to_send_code": "åééªè¯ç å¤±è´¥",
    "failed_to_verify": "éªè¯å¤±è´¥",
    "filter": "ç­é",
    "friends_count": "ä½å¥½å",
    "friends_referred": "æ¨èçå¥½å",
    "github": "GitHub",
    "github_connect_description": "è¿æ¥æ¨ç GitHub è´¦æ·ä»¥å¯¼å¥ä»åº",
    "github_integration": "GitHub éæ",
    "help_support": "å¸®å©ä¸æ¯æ",
    "help_support_subtitle": "è·åå¸®å©ä¸æ¯æ",
    "import_action": "å¯¼å¥",
    "import_dialog_description": "è¾å¥æ¨è¦å¯¼å¥çä»åºä¿¡æ¯",
    "import_dialog_title": "å¯¼å¥å¬å±ä»åº",
    "import_failed": "å¯¼å¥ä»åºå¤±è´¥",
    "import_repository": "å¯¼å¥ä»åº",
    "import_subtitle": "å¯¼å¥å¬å±ä»åº",
    "import_success": "ä»åºå¯¼å¥æå",
    "importing": "å¯¼å¥ä¸­...",
    "industry": "è¡ä¸",
    "input_error_owner_repo": "è¯·è¾å¥æ¥æèåä»åºåç§°",
    "invite_code_copied": "éè¯·ç å·²å¤å¶å°åªè´´æ¿",
    "invite_code_unavailable": "éè¯·ç ä¸å¯ç¨",
    "invite_description": "éè¯·å¥½åå å¥ d1v.ai å¹¶è·å¾å¥å±",
    "invite_friends": "éè¯·å¥½å",
    "invites": "éè¯·",
    "just_now": "åå",
    "language": "è¯­è¨",
    "legend_less": "å°",
    "legend_more": "å¤",
    "light_mode": "æµè²æ¨¡å¼",
    "loading": "å è½½ä¸­...",
    "login": "ç»å½",
    "login_failed": "ç»å½å¤±è´¥",
    "login_first": "è¯·åç»å½",
    "login_required_button": "å»ç»å½",
    "login_required_create_post_message": "ä½ éè¦åç»å½æè½åå¸å¸å­",
    "login_required_dashboard_message": "ä½ éè¦åç»å½æè½æ¥çé¡¹ç®åè¡¨",
    "login_required_github_message": "ä½ éè¦åç»å½æè½éç½® GitHub éæ",
    "login_required_invites_message": "ä½ éè¦åç»å½æè½æ¥çéè¯·ä¸å¥å±",
    "login_required_orders_message": "ä½ éè¦åç»å½æè½æ¥çè®¢åä¸è®¡è´¹ä¿¡æ¯",
    "login_required_settings_message": "ä½ éè¦åç»å½æè½ç®¡çè´¦å·è®¾ç½®",
    "login_required_title": "éè¦ç»å½",
    "login_success": "ç»å½æå",
    "login_with_code": "éªè¯ç ç»å½",
    "login_with_password": "å¯ç ç»å½",
    "logout": "éåºç»å½",
    "my_invites": "æçéè¯·",
    "my_invites_subtitle": "æ¥çæ¨çéè¯·åå²",
    "new_password": "æ°å¯ç ",
    "no_posts_yet": "ææ åå®¹",
    "notifications": "éç¥",
    "notifications_subtitle": "ç®¡çéç¥",
    "other": "å¶ä»",
    "owner_hint": "ç¨æ·åæç»ç»å",
    "owner_label": "æ¥æè",
    "password": "å¯ç ",
    "password_length_error": "å¯ç é¿åº¦è³å°ä¸º6ä¸ªå­ç¬¦",
    "password_required": "è¯·è¾å¥å¯ç ",
    "password_reset_success": "å¯ç éç½®æå",
    "passwords_do_not_match": "ä¸¤æ¬¡è¾å¥çå¯ç ä¸ä¸è´",
    "pricing": "ä»·æ ¼æ¹æ¡",
    "privacy": "éç§",
    "profile": "ä¸ªäººä¸­å¿",
    "project_name_hint": "çç©ºä½¿ç¨ä»åºåç§°",
    "project_name_optional": "é¡¹ç®åç§° (å¯é)",
    "prompt_activity_title": "æç¤ºè¯æ´»è·åº¦",
    "prompt_activity_total": "æ»è®¡ï¼",
    "prompts_unit": "æ¬¡",
    "re_enter_new_password": "è¯·åæ¬¡è¾å¥æ°å¯ç ",
    "recent_projects": "è¿æé¡¹ç®",
    "refresh": "å·æ°",
    "repo_hint": "ä»åºåç§°",
    "repo_label": "ä»åº",
    "resend_after": "ç§åéå",
    "resend_code": "éæ°åééªè¯ç ",
    "reset_password": "éç½®å¯ç ",
    "reset_password_subtitle": "éç½®æ¨çç»å½å¯ç ",
    "resetting": "éç½®ä¸­...",
    "retry": "éè¯",
    "save": "ä¿å­",
    "save_changes": "ä¿å­æ´æ¹",
    "search": "æç´¢",
    "send_code": "åééªè¯ç ",
    "sending": "åéä¸­...",
    "session_expired_message": "ç»å½å·²è¿æï¼è¯·éæ°ç»å½",
    "session_expired_title": "ç»å½å·²è¿æ",
    "settings": "è®¾ç½®",
    "share_failed": "åäº«å¤±è´¥",
    "share_invite_code": "åäº«éè¯·ç ",
    "share_message_subject": "å å¥ d1v.ai",
    "share_success": "éè¯·ç åäº«æå",
    "sort": "æåº",
    "success": "æå",
    "sync_failed": "åæ­¥ä»åºå¤±è´¥",
    "sync_repositories": "åæ­¥ä»åº",
    "sync_subtitle": "æ´æ°æ¨çä»åºåè¡¨",
    "sync_success": "ä»åºåæ­¥æå",
    "syncing": "åæ­¥ä¸­",
    "syncing_message": "æ­£å¨åæ­¥ä»åº...",
    "system_mode": "è·éç³»ç»",
    "theme_subtitle": "æäº®ææ·±è²æ¨¡å¼",
    "theme_switched": "å·²åæ¢è³",
    "theme_title": "ä¸»é¢",
    "theme_updated": "ä¸»é¢å·²æ´æ°",
    "verify_code": "éªè¯ç ",
    "verify_code_complete": "è¯·è¾å¥å®æ´çéªè¯ç ",
    "verify_code_required": "è¯·è¾å¥éªè¯ç ",
    "verify_login": "éªè¯ç»å½",
    "verifying": "éªè¯ä¸­...",
    "wallet_addresses": "é±åå°å",
    "welcome": "æ¬¢è¿",
    "your_invite_code": "æ¨çéè¯·ç ",
  },
  "zh_Hant": <String, String>{
    "about": "éæ¼",
    "about_description": "ä¸å AI é©åçæç¨ç¨å¼éç¼å¹³å°ã",
    "about_subtitle": "æç¨çæ¬åè³è¨",
    "about_title": "éæ¼",
    "activity": "åæ",
    "agree_terms": "ç»å¥å³è¡¨ç¤ºæ¨åææåçæåæ¢æ¬¾åé±ç§æ¿ç­",
    "api_settings": "API",
    "appearance": "å¤è§",
    "basic_information": "åºæ¬è³è¨",
    "be_first_to_share": "æ¶åç¼ä½ç¬¬ä¸ååæ",
    "bind_email": "ç¶å®é»å­éµä»¶",
    "bind_email_subtitle": "ç¶å®é»å­éµä»¶å°æ¨çå¸³æ¶",
    "cancel": "åæ¶",
    "choose_theme": "é¸æä¸»é¡",
    "code_sent_success": "é©è­ç¢¼å·²ç¼éï¼è«æ¥æ¶éµä»¶",
    "code_sent_to": "é©è­ç¢¼å·²ç¼éè³",
    "community": "ç¤¾ç¾¤",
    "company_name": "å¬å¸åç¨±",
    "company_website": "å¬å¸ç¶²ç«",
    "confirm": "ç¢ºèª",
    "confirm_password": "ç¢ºèªå¯ç¢¼",
    "connect_github": "é£æ¥ GitHub",
    "contact_support": "è¯çµ¡å®¢æ",
    "copied": "å·²è¤è£½",
    "create_project": "å»ºç«å°æ¡",
    "dark_mode": "æ·±è²æ¨¡å¼",
    "dashboard": "å·¥ä½å°",
    "delete": "åªé¤",
    "docs": "æä»¶",
    "edit": "ç·¨è¼¯",
    "edit_profile": "ç·¨è¼¯è³æ",
    "email": "é»å­éµä»¶",
    "email_address": "é»å­éµä»¶å°å",
    "email_bound_success": "é»å­éµä»¶ç¶å®æå",
    "email_invalid": "è«è¼¸å¥ææçé»å­éµä»¶å°å",
    "email_required": "è«è¼¸å¥é»å­éµä»¶å°å",
    "enter_code_and_new_password": "è¼¸å¥é©è­ç¢¼åæ°å¯ç¢¼",
    "enter_code_sent": "è¼¸å¥ç¼éå°æ¨é»å­éµä»¶ç6ä½é©è­ç¢¼",
    "enter_email": "è«è¼¸å¥æ¨çé»å­éµä»¶",
    "enter_email_for_code": "è¼¸å¥é»å­éµä»¶å°åä»¥æ¥æ¶é©è­ç¢¼",
    "enter_new_password": "è«è¼¸å¥æ°å¯ç¢¼",
    "enter_password": "è«è¼¸å¥å¯ç¢¼",
    "enter_verify_code": "è«è¼¸å¥é©è­ç¢¼",
    "error": "é¯èª¤",
    "error_network": "ç¶²è·¯é£ç·å¤±æï¼è«æª¢æ¥ç¶²è·¯å¾éè©¦",
    "error_request_failed": "è«æ±å¤±æï¼è«ç¨å¾éè©¦",
    "error_timeout": "è«æ±é¾æï¼è«ç¨å¾éè©¦",
    "failed_to_load": "è¼å¥å¤±æ",
    "failed_to_load_posts": "å§å®¹è¼å¥å¤±æ",
    "failed_to_reset_password": "éç½®å¯ç¢¼å¤±æ",
    "failed_to_send_code": "ç¼éé©è­ç¢¼å¤±æ",
    "failed_to_verify": "é©è­å¤±æ",
    "filter": "ç¯©é¸",
    "friends_count": "ä½å¥½å",
    "friends_referred": "æ¨è¦çå¥½å",
    "github": "GitHub",
    "github_connect_description": "é£æ¥æ¨ç GitHub å¸³æ¶ä»¥å¯å¥å²å­åº«",
    "github_integration": "GitHub æ´å",
    "help_support": "å¹«å©èæ¯æ´",
    "help_support_subtitle": "ç²åå¹«å©èæ¯æ´",
    "import_action": "å¯å¥",
    "import_dialog_description": "è¼¸å¥æ¨è¦å¯å¥çå²å­åº«è³è¨",
    "import_dialog_title": "å¯å¥å¬å±å²å­åº«",
    "import_failed": "å¯å¥å²å­åº«å¤±æ",
    "import_repository": "å¯å¥å²å­åº«",
    "import_subtitle": "å¯å¥å¬å±å²å­åº«",
    "import_success": "å²å­åº«å¯å¥æå",
    "importing": "å¯å¥ä¸­...",
    "industry": "ç¢æ¥­",
    "input_error_owner_repo": "è«è¼¸å¥ææèåå²å­åº«åç¨±",
    "invite_code_copied": "éè«ç¢¼å·²è¤è£½å°åªè²¼ç°¿",
    "invite_code_unavailable": "éè«ç¢¼ä¸å¯ç¨",
    "invite_description": "éè«å¥½åå å¥ d1v.ai ä¸¦ç²å¾çåµ",
    "invite_friends": "éè«å¥½å",
    "invites": "éè«",
    "just_now": "åå",
    "language": "èªè¨",
    "legend_less": "å°",
    "legend_more": "å¤",
    "light_mode": "æ·ºè²æ¨¡å¼",
    "loading": "è¼å¥ä¸­...",
    "login": "ç»å¥",
    "login_failed": "ç»å¥å¤±æ",
    "login_first": "è«åç»å¥",
    "login_required_button": "åå¾ç»å¥",
    "login_required_create_post_message": "ä½ éè¦åç»å¥æè½ç¼ä½è²¼æ",
    "login_required_dashboard_message": "ä½ éè¦åç»å¥æè½æ¥çå°æ¡åè¡¨",
    "login_required_github_message": "ä½ éè¦åç»å¥æè½è¨­å® GitHub æ´å",
    "login_required_invites_message": "ä½ éè¦åç»å¥æè½æ¥çéè«èçåµ",
    "login_required_orders_message": "ä½ éè¦åç»å¥æè½æ¥çè¨å®èè¨è²»è³è¨",
    "login_required_settings_message": "ä½ éè¦åç»å¥æè½ç®¡çå¸³èè¨­å®",
    "login_required_title": "éè¦ç»å¥",
    "login_success": "ç»å¥æå",
    "login_with_code": "ä½¿ç¨é©è­ç¢¼ç»å¥",
    "login_with_password": "ä½¿ç¨å¯ç¢¼ç»å¥",
    "logout": "ç»åº",
    "my_invites": "æçéè«",
    "my_invites_subtitle": "æ¥çæ¨çéè«è¨é",
    "new_password": "æ°å¯ç¢¼",
    "no_posts_yet": "æ«ç¡å§å®¹",
    "notifications": "éç¥",
    "notifications_subtitle": "ç®¡çéç¥",
    "other": "å¶ä»",
    "owner_hint": "ä½¿ç¨èåç¨±æçµç¹",
    "owner_label": "ææè",
    "password": "å¯ç¢¼",
    "password_length_error": "å¯ç¢¼é·åº¦è³å°çº6åå­å",
    "password_required": "è«è¼¸å¥å¯ç¢¼",
    "password_reset_success": "å¯ç¢¼éç½®æå",
    "passwords_do_not_match": "å©æ¬¡è¼¸å¥çå¯ç¢¼ä¸ä¸è´",
    "pricing": "æ¹æ¡å¹æ ¼",
    "privacy": "é±ç§",
    "profile": "åäººä¸­å¿",
    "project_name_hint": "çç©ºä½¿ç¨å²å­åº«åç¨±",
    "project_name_optional": "å°æ¡åç¨± (å¯é¸)",
    "prompt_activity_title": "æç¤ºè©æ´»èºåº¦",
    "prompt_activity_total": "ç¸½è¨ï¼",
    "prompts_unit": "æ¬¡",
    "re_enter_new_password": "è«åæ¬¡è¼¸å¥æ°å¯ç¢¼",
    "recent_projects": "è¿æå°æ¡",
    "refresh": "éæ°æ´ç",
    "repo_hint": "å²å­åº«åç¨±",
    "repo_label": "å²å­åº«",
    "resend_after": "ç§å¾éç¼",
    "resend_code": "éæ°ç¼éé©è­ç¢¼",
    "reset_password": "éç½®å¯ç¢¼",
    "reset_password_subtitle": "éç½®æ¨çç»å¥å¯ç¢¼",
    "resetting": "éç½®ä¸­...",
    "retry": "éè©¦",
    "save": "å²å­",
    "save_changes": "å²å­è®æ´",
    "search": "æå°",
    "send_code": "ç¼éé©è­ç¢¼",
    "sending": "ç¼éä¸­...",
    "session_expired_message": "ç»å¥å·²éæï¼è«éæ°ç»å¥",
    "session_expired_title": "ç»å¥å·²éæ",
    "settings": "è¨­å®",
    "share_failed": "åäº«å¤±æ",
    "share_invite_code": "åäº«éè«ç¢¼",
    "share_message_subject": "å å¥ d1v.ai",
    "share_success": "éè«ç¢¼åäº«æå",
    "sort": "æåº",
    "success": "æå",
    "sync_failed": "åæ­¥å²å­åº«å¤±æ",
    "sync_repositories": "åæ­¥å²å­åº«",
    "sync_subtitle": "æ´æ°æ¨çå²å­åº«åè¡¨",
    "sync_success": "å²å­åº«åæ­¥æå",
    "syncing": "åæ­¥ä¸­",
    "syncing_message": "æ­£å¨åæ­¥å²å­åº«...",
    "system_mode": "è·é¨ç³»çµ±",
    "theme_subtitle": "æäº®ææ·±è²æ¨¡å¼",
    "theme_switched": "å·²åæè³",
    "theme_title": "ä¸»é¡",
    "theme_updated": "ä¸»é¡å·²æ´æ°",
    "verify_code": "é©è­ç¢¼",
    "verify_code_complete": "è«è¼¸å¥å®æ´çé©è­ç¢¼",
    "verify_code_required": "è«è¼¸å¥é©è­ç¢¼",
    "verify_login": "é©è­ç»å¥",
    "verifying": "é©è­ä¸­...",
    "wallet_addresses": "é¢åå°å",
    "welcome": "æ­¡è¿",
    "your_invite_code": "æ¨çéè«ç¢¼",
  },
};
